# See docs at https://goreleaser.com/customization/build
project_name: webrpc

builds:
  - main: ./cmd/webrpc-gen
    binary: webrpc-gen
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm64

archives:
  - name_template: "{{ .Binary }}.{{ .Os }}-{{ .Arch }}"
    format: binary

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
  sort: asc
