# See documentation at https://goreleaser.com/customization/build.
project_name: webrpc

builds:
  - main: ./cmd/webrpc-gen
    binary: webrpc-gen
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/webrpc/webrpc/gen.VERSION=v{{.Version}}

archives:
  - name_template: "{{ .Binary }}.{{ .Os }}-{{ .Arch }}"
    format: binary

checksum:
  name_template: "checksums.txt"

release:
  header: |
    ## Docker
    ```
    docker run ghcr.io/webrpc/webrpc-gen:v{{.Version}}
    ```

    ## Homebrew
    ```
    brew install webrpc/tap/webrpc-gen
    ```

    ## Build & install from source manually
    ```
    go install github.com/webrpc/webrpc/cmd/webrpc-gen
    ```

changelog:
  use: github
  sort: asc

brews:
  - name: webrpc-gen
    tap:
      owner: webrpc
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/webrpc/webrpc"
    description: "generate source code for your target language from webrpc schema"
    license: "MIT"
