/* tslint:disable */
// hello-webrpc v1.0.0
// --
// This file has been generated by https://github.com/webrpc/webrpc using gen/typescript
// Do not edit by hand. Update your webrpc schema and re-generate.


export enum Kind {
  USER = 'USER',
  ADMIN = 'ADMIN'
}

export interface IUser {
  id: number
  USERNAME: string
  role: Kind
  meta: object
  created_at?: string
  toJSON?(): object
}

export class User implements IUser {
  private _data: IUser
  constructor(_data?: IUser) {
    this._data = {} as IUser
    if (_data) {
      this._data['id'] = _data['id']!
      this._data['USERNAME'] = _data['USERNAME']!
      this._data['role'] = _data['role']!
      this._data['meta'] = _data['meta']!
      this._data['created_at'] = _data['created_at']!
      
    }
  }
  public get id(): number {
    return this._data['id']!
  }
  public set id(value: number) {
    this._data['id'] = value
  }
  public get USERNAME(): string {
    return this._data['USERNAME']!
  }
  public set USERNAME(value: string) {
    this._data['USERNAME'] = value
  }
  public get role(): Kind {
    return this._data['role']!
  }
  public set role(value: Kind) {
    this._data['role'] = value
  }
  public get meta(): object {
    return this._data['meta']!
  }
  public set meta(value: object) {
    this._data['meta'] = value
  }
  public get created_at(): string {
    return this._data['created_at']!
  }
  public set created_at(value: string) {
    this._data['created_at'] = value
  }
  
  public toJSON(): object {
    return this._data
  }
}

export interface IPage {
  num?: number
  toJSON?(): object
}

export class Page implements IPage {
  private _data: IPage
  constructor(_data?: IPage) {
    this._data = {} as IPage
    if (_data) {
      this._data['num'] = _data['num']!
      
    }
  }
  public get num(): number {
    return this._data['num']!
  }
  public set num(value: number) {
    this._data['num'] = value
  }
  
  public toJSON(): object {
    return this._data
  }
}
export interface IExampleService {
  ping(headers: object): Promise<IPingReturn>
  getUser(args: IGetUserArgs, headers: object): Promise<IGetUserReturn>
  findUsers(args: IFindUsersArgs, headers: object): Promise<IFindUsersReturn>
  
}

export interface IPingArgs {
}

export interface IPingReturn {
  status: boolean  
}
export interface IGetUserArgs {
  userID: number
}

export interface IGetUserReturn {
  user: IUser  
}
export interface IFindUsersArgs {
  q: string
}

export interface IFindUsersReturn {
  page: IPage
  users: Array<IUser>  
}


  
// Client

const ExampleServicePathPrefix = "/rpc/ExampleService/"

export class ExampleService implements IExampleService {
  private hostname: string
  private fetch: Fetch
  private path = '/rpc/ExampleService/'

  constructor(hostname: string, fetch: Fetch) {
    this.hostname = hostname
    this.fetch = fetch
  }

  private url(name: string): string {
    return this.hostname + this.path + name
  }

  
  ping(headers: object = {}): Promise<IPingReturn> {
    return this.fetch(
      this.url('Ping'),
      
      createHTTPRequest({}, headers)
      
    ).then((res) => {
      if (!res.ok) {
        return throwHTTPError(res)
      }
      return res.json().then((_data) => {
        return {
          status: <boolean>(_data.status)
        }
      })
    })
  }
  
  getUser(args: IGetUserArgs, headers: object = {}): Promise<IGetUserReturn> {
    return this.fetch(
      this.url('GetUser'),
      
      createHTTPRequest(args, headers)
      
    ).then((res) => {
      if (!res.ok) {
        return throwHTTPError(res)
      }
      return res.json().then((_data) => {
        return {
          user: new User(_data.user)
        }
      })
    })
  }
  
  findUsers(args: IFindUsersArgs, headers: object = {}): Promise<IFindUsersReturn> {
    return this.fetch(
      this.url('FindUsers'),
      
      createHTTPRequest(args, headers)
      
    ).then((res) => {
      if (!res.ok) {
        return throwHTTPError(res)
      }
      return res.json().then((_data) => {
        return {
          page: new Page(_data.page), 
          users: <Array<IUser>>(_data.users)
        }
      })
    })
  }
  
}



export interface WebRPCError extends Error {
  code: string
  msg: string
	status: number
}

export const throwHTTPError = (resp: Response) => {
  return resp.json().then((err: WebRPCError) => { throw err })
}

export const createHTTPRequest = (body: object = {}, headers: object = {}): object => {
  return {
    method: 'POST',
    headers: { ...headers, 'Content-Type': 'application/json' },
    body: JSON.stringify(body || {})
  }
}

export type Fetch = (input: RequestInfo, init?: RequestInit) => Promise<Response>
