/* eslint-disable */
// Test v1.0.0 95498be344c43f13a61e87c8fa2a6cc9d2d7df7c
// --
// Code generated by Webrpc-gen with typescript generator. DO NOT EDIT.
//
// webrpc-gen -schema=../schema/test.ridl -target=typescript -client -service=TestApiRest -out=./restClient.gen.ts
// Webrpc description and code-gen version
export const WebrpcVersion = "v1"

// Schema version of your RIDL schema
export const WebrpcSchemaVersion = "v1.0.0"

// Schema hash generated from your RIDL schema
export const WebrpcSchemaHash = "95498be344c43f13a61e87c8fa2a6cc9d2d7df7c"

//
// Client interface
//

export interface TestApiRestClient {
  getItem(req: GetItemRequest, headers?: object, signal?: AbortSignal): Promise<GetItemResponse>

  listItems(req: ListItemsRequest, headers?: object, signal?: AbortSignal): Promise<ListItemsResponse>

  createItem(req: CreateItemRequest, headers?: object, signal?: AbortSignal): Promise<CreateItemResponse>

  updateItem(req: UpdateItemRequest, headers?: object, signal?: AbortSignal): Promise<UpdateItemResponse>

  patchItem(req: PatchItemRequest, headers?: object, signal?: AbortSignal): Promise<PatchItemResponse>

  deleteItem(req: DeleteItemRequest, headers?: object, signal?: AbortSignal): Promise<DeleteItemResponse>

  queryItems(req: QueryItemsRequest, headers?: object, signal?: AbortSignal): Promise<QueryItemsResponse>

  echoParams(req: EchoParamsRequest, headers?: object, signal?: AbortSignal): Promise<EchoParamsResponse>

  getChild(req: GetChildRequest, headers?: object, signal?: AbortSignal): Promise<GetChildResponse>

  resetItems(headers?: object, signal?: AbortSignal): Promise<ResetItemsResponse>

  rpcMethod(req: RpcMethodRequest, headers?: object, signal?: AbortSignal): Promise<RpcMethodResponse>
}


//
// Schema types
//

export enum Status {
  AVAILABLE = 'AVAILABLE',
  NOT_AVAILABLE = 'NOT_AVAILABLE'
}

export enum Access {
  NONE = 'NONE',
  READ = 'READ',
  WRITE = 'WRITE',
  ADMIN = 'ADMIN',
  OWNER = 'OWNER'
}

export interface Item {
  id: number
  name: string
}

export interface GetItemRequest {
  id: number
  details?: boolean
}

export interface GetItemResponse {
  item: Item
}

export interface ListItemsRequest {
  q?: string
  tags: Array<string>
  limit: number
}

export interface ListItemsResponse {
  items: Array<Item>
}

export interface CreateItemRequest {
  item: Item
}

export interface CreateItemResponse {
  item: Item
}

export interface Simple {
  id: number
  name: string
}

export interface User {
  id: number
  USERNAME: string
  role: string
}

export interface Complex {
  meta: {[key: string]: any}
  metaNestedExample: {[key: string]: {[key: string]: number}}
  namesList: Array<string>
  numsList: Array<number>
  doubleArray: Array<Array<string>>
  listOfMaps: Array<{[key: string]: number}>
  listOfUsers: Array<User>
  mapOfUsers: {[key: string]: User}
  user: User
  status: Status
}

export interface EnumData {
  dict: {[key in Access]?: number}
  list: Array<Status>
}




export interface UpdateItemRequest {
  id: number
  name: string
}

export interface UpdateItemResponse {
  item: Item
}

export interface PatchItemRequest {
  id: number
  name?: string
}

export interface PatchItemResponse {
  item: Item
}

export interface DeleteItemRequest {
  id: number
}

export interface DeleteItemResponse {
}

export interface QueryItemsRequest {
  q: string
}

export interface QueryItemsResponse {
  items: Array<Item>
}

export interface EchoParamsRequest {
  str: string
  num: number
  flag: boolean
  fl: number
  ts: string
  status: Status
  tags: Array<string>
  opt?: string
}

export interface EchoParamsResponse {
  echo: string
}

export interface GetChildRequest {
  id: number
  childId: number
}

export interface GetChildResponse {
  path: string
}

export interface ResetItemsRequest {
}

export interface ResetItemsResponse {
}

export interface RpcMethodRequest {
  id: number
}

export interface RpcMethodResponse {
  item: Item
}



//
// Client
//

export class TestApiRest implements TestApiRestClient {
  protected hostname: string
  protected fetch: Fetch
  protected path = '/rpc/TestApiRest/'

  constructor(hostname: string, fetch: Fetch) {
    this.hostname = hostname.replace(/\/*$/, '')
    this.fetch = (input: RequestInfo, init?: RequestInit) => fetch(input, init)
  }

  private url(name: string): string {
    return this.hostname + this.path + name
  }
  
  queryKey = {
    getItem: (req: GetItemRequest) => ['TestApiRest', 'getItem', req] as const,
    listItems: (req: ListItemsRequest) => ['TestApiRest', 'listItems', req] as const,
    createItem: (req: CreateItemRequest) => ['TestApiRest', 'createItem', req] as const,
    updateItem: (req: UpdateItemRequest) => ['TestApiRest', 'updateItem', req] as const,
    patchItem: (req: PatchItemRequest) => ['TestApiRest', 'patchItem', req] as const,
    deleteItem: (req: DeleteItemRequest) => ['TestApiRest', 'deleteItem', req] as const,
    queryItems: (req: QueryItemsRequest) => ['TestApiRest', 'queryItems', req] as const,
    echoParams: (req: EchoParamsRequest) => ['TestApiRest', 'echoParams', req] as const,
    getChild: (req: GetChildRequest) => ['TestApiRest', 'getChild', req] as const,
    resetItems: () => ['TestApiRest', 'resetItems'] as const,
    rpcMethod: (req: RpcMethodRequest) => ['TestApiRest', 'rpcMethod', req] as const,
  }

  getItem = (req: GetItemRequest, headers?: object, signal?: AbortSignal): Promise<GetItemResponse> => {
    return this.fetch(
      ...createHttpRestRequest(this.hostname, 'GET', '/rpc/items/{id}', req, headers, signal)).then((res) => {
      return buildResponse(res).then(_data => {
        return JsonDecode<GetItemResponse>(_data, 'GetItemResponse')
      })
    }, (error) => {
      throw WebrpcRequestFailedError.new({ cause: `fetch(): ${error instanceof Error ? error.message : String(error)}` })
    })
  }

  listItems = (req: ListItemsRequest, headers?: object, signal?: AbortSignal): Promise<ListItemsResponse> => {
    return this.fetch(
      ...createHttpRestRequest(this.hostname, 'GET', '/rpc/items', req, headers, signal)).then((res) => {
      return buildResponse(res).then(_data => {
        return JsonDecode<ListItemsResponse>(_data, 'ListItemsResponse')
      })
    }, (error) => {
      throw WebrpcRequestFailedError.new({ cause: `fetch(): ${error instanceof Error ? error.message : String(error)}` })
    })
  }

  createItem = (req: CreateItemRequest, headers?: object, signal?: AbortSignal): Promise<CreateItemResponse> => {
    return this.fetch(
      ...createHttpRestRequest(this.hostname, 'POST', '/rpc/items', req, headers, signal)).then((res) => {
      return buildResponse(res).then(_data => {
        return JsonDecode<CreateItemResponse>(_data, 'CreateItemResponse')
      })
    }, (error) => {
      throw WebrpcRequestFailedError.new({ cause: `fetch(): ${error instanceof Error ? error.message : String(error)}` })
    })
  }

  updateItem = (req: UpdateItemRequest, headers?: object, signal?: AbortSignal): Promise<UpdateItemResponse> => {
    return this.fetch(
      ...createHttpRestRequest(this.hostname, 'PUT', '/rpc/items/{id}', req, headers, signal)).then((res) => {
      return buildResponse(res).then(_data => {
        return JsonDecode<UpdateItemResponse>(_data, 'UpdateItemResponse')
      })
    }, (error) => {
      throw WebrpcRequestFailedError.new({ cause: `fetch(): ${error instanceof Error ? error.message : String(error)}` })
    })
  }

  patchItem = (req: PatchItemRequest, headers?: object, signal?: AbortSignal): Promise<PatchItemResponse> => {
    return this.fetch(
      ...createHttpRestRequest(this.hostname, 'PATCH', '/rpc/items/{id}', req, headers, signal)).then((res) => {
      return buildResponse(res).then(_data => {
        return JsonDecode<PatchItemResponse>(_data, 'PatchItemResponse')
      })
    }, (error) => {
      throw WebrpcRequestFailedError.new({ cause: `fetch(): ${error instanceof Error ? error.message : String(error)}` })
    })
  }

  deleteItem = (req: DeleteItemRequest, headers?: object, signal?: AbortSignal): Promise<DeleteItemResponse> => {
    return this.fetch(
      ...createHttpRestRequest(this.hostname, 'DELETE', '/rpc/items/{id}', req, headers, signal)).then((res) => {
      return buildResponse(res).then(_data => {
        return JsonDecode<DeleteItemResponse>(_data, 'DeleteItemResponse')
      })
    }, (error) => {
      throw WebrpcRequestFailedError.new({ cause: `fetch(): ${error instanceof Error ? error.message : String(error)}` })
    })
  }

  queryItems = (req: QueryItemsRequest, headers?: object, signal?: AbortSignal): Promise<QueryItemsResponse> => {
    return this.fetch(
      ...createHttpRestRequest(this.hostname, 'QUERY', '/rpc/items/search', req, headers, signal)).then((res) => {
      return buildResponse(res).then(_data => {
        return JsonDecode<QueryItemsResponse>(_data, 'QueryItemsResponse')
      })
    }, (error) => {
      throw WebrpcRequestFailedError.new({ cause: `fetch(): ${error instanceof Error ? error.message : String(error)}` })
    })
  }

  echoParams = (req: EchoParamsRequest, headers?: object, signal?: AbortSignal): Promise<EchoParamsResponse> => {
    return this.fetch(
      ...createHttpRestRequest(this.hostname, 'GET', '/rpc/items/echo/params', req, headers, signal)).then((res) => {
      return buildResponse(res).then(_data => {
        return JsonDecode<EchoParamsResponse>(_data, 'EchoParamsResponse')
      })
    }, (error) => {
      throw WebrpcRequestFailedError.new({ cause: `fetch(): ${error instanceof Error ? error.message : String(error)}` })
    })
  }

  getChild = (req: GetChildRequest, headers?: object, signal?: AbortSignal): Promise<GetChildResponse> => {
    return this.fetch(
      ...createHttpRestRequest(this.hostname, 'GET', '/rpc/items/{id}/children/{childId}', req, headers, signal)).then((res) => {
      return buildResponse(res).then(_data => {
        return JsonDecode<GetChildResponse>(_data, 'GetChildResponse')
      })
    }, (error) => {
      throw WebrpcRequestFailedError.new({ cause: `fetch(): ${error instanceof Error ? error.message : String(error)}` })
    })
  }

  resetItems = (headers?: object, signal?: AbortSignal): Promise<ResetItemsResponse> => {
    return this.fetch(
      ...createHttpRestRequest(this.hostname, 'POST', '/rpc/items/reset', {}, headers, signal)).then((res) => {
      return buildResponse(res).then(_data => {
        return JsonDecode<ResetItemsResponse>(_data, 'ResetItemsResponse')
      })
    }, (error) => {
      throw WebrpcRequestFailedError.new({ cause: `fetch(): ${error instanceof Error ? error.message : String(error)}` })
    })
  }

  rpcMethod = (req: RpcMethodRequest, headers?: object, signal?: AbortSignal): Promise<RpcMethodResponse> => {
    return this.fetch(
      this.url('RpcMethod'),
      createHttpRequest(JsonEncode(req), headers, signal)).then((res) => {
      return buildResponse(res).then(_data => {
        return JsonDecode<RpcMethodResponse>(_data, 'RpcMethodResponse')
      })
    }, (error) => {
      throw WebrpcRequestFailedError.new({ cause: `fetch(): ${error instanceof Error ? error.message : String(error)}` })
    })
  }

}

const createHttpRequest = (body: string = '{}', headers: object = {}, signal: AbortSignal | null = null): object => {
  const reqHeaders: { [key: string]: string } = { ...headers, 'Content-Type': 'application/json', [WebrpcHeader]: WebrpcHeaderValue }
  return { method: 'POST', headers: reqHeaders, body, signal }
}

// createHttpRestRequest returns the fetch() arguments of a REST route call:
// request fields named by {param} placeholders fill the path, the others go
// to the query string (GET/DELETE/QUERY) or the JSON body.
const createHttpRestRequest = (hostname: string, method: string, path: string, req: object, headers: object = {}, signal: AbortSignal | null = null): [string, object] => {
  const fields: { [key: string]: any } = JSON.parse(JsonEncode(req))
  const hasBody = method === 'POST' || method === 'PUT' || method === 'PATCH'
  const query = new URLSearchParams()
  path = path.replace(/\{(\w+)\}/g, (_, name) => {
    const value = fields[name]
    delete fields[name]
    return encodeURIComponent(String(value))
  })
  if (!hasBody) {
    for (const [name, value] of Object.entries(fields)) {
      for (const v of Array.isArray(value) ? value : value == null ? [] : [value]) {
        query.append(name, String(v))
      }
    }
  }
  const qs = query.toString()
  const reqHeaders: { [key: string]: string } = { ...headers, [WebrpcHeader]: WebrpcHeaderValue }
  if (hasBody) {
    reqHeaders['Content-Type'] = 'application/json'
  }
  return [hostname + path + (qs ? '?' + qs : ''), { method, headers: reqHeaders, body: hasBody ? JsonEncode(req) : undefined, signal }]
}

const buildResponse = (res: Response): Promise<any> => {
  return res.text().then(text => {
    let data
    try {
      data = JSON.parse(text)
    } catch(error) {
      throw WebrpcBadResponseError.new({
        status: res.status,
        cause: `JSON.parse(): ${error instanceof Error ? error.message : String(error)}: response text: ${text}`},
      )
    }
    if (!res.ok) {
      const code: number = (typeof data.code === 'number') ? data.code : 0
      throw (webrpcErrorByCode[code] || WebrpcError).new(data)
    }
    return data
  })
}

export type Fetch = (input: RequestInfo, init?: RequestInit) => Promise<Response>






export const JsonEncode = <T = any>(obj: T): string => {
  return JSON.stringify(obj)
}

export const JsonDecode = <T = any>(data: string | any, _typ: string = ''): T => {
  let parsed: any = data
  if (typeof data === 'string') {
    try { parsed = JSON.parse(data) } catch (err) {
      throw WebrpcBadResponseError.new({ cause: `JsonDecode: JSON.parse failed: ${(err as Error).message}` })
    }
  }
  return parsed as T
}


//
// Errors
//

type WebrpcErrorParams = { name?: string, code?: number, message?: string, status?: number, cause?: string }

export class WebrpcError extends Error {
  code: number
  status: number

  constructor(error: WebrpcErrorParams = {}) {
    super(error.message)
    this.name = error.name || 'WebrpcEndpointError'
    this.code = typeof error.code === 'number' ? error.code : 0
    this.message = error.message || `endpoint error`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcError.prototype)
  }

  static new(payload: any): WebrpcError {
    return new this({ message: payload.message, code: payload.code, status: payload.status, cause: payload.cause })
  }
}


export class WebrpcEndpointError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcEndpoint'
    this.code = typeof error.code === 'number' ? error.code : 0
    this.message = error.message || `endpoint error`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcEndpointError.prototype)
  }
}

export class WebrpcRequestFailedError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcRequestFailed'
    this.code = typeof error.code === 'number' ? error.code : -1
    this.message = error.message || `request failed`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcRequestFailedError.prototype)
  }
}

export class WebrpcBadRouteError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcBadRoute'
    this.code = typeof error.code === 'number' ? error.code : -2
    this.message = error.message || `bad route`
    this.status = typeof error.status === 'number' ? error.status : 404
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcBadRouteError.prototype)
  }
}

export class WebrpcBadMethodError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcBadMethod'
    this.code = typeof error.code === 'number' ? error.code : -3
    this.message = error.message || `bad method`
    this.status = typeof error.status === 'number' ? error.status : 405
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcBadMethodError.prototype)
  }
}

export class WebrpcBadRequestError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcBadRequest'
    this.code = typeof error.code === 'number' ? error.code : -4
    this.message = error.message || `bad request`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcBadRequestError.prototype)
  }
}

export class WebrpcBadResponseError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcBadResponse'
    this.code = typeof error.code === 'number' ? error.code : -5
    this.message = error.message || `bad response`
    this.status = typeof error.status === 'number' ? error.status : 500
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcBadResponseError.prototype)
  }
}

export class WebrpcServerPanicError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcServerPanic'
    this.code = typeof error.code === 'number' ? error.code : -6
    this.message = error.message || `server panic`
    this.status = typeof error.status === 'number' ? error.status : 500
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcServerPanicError.prototype)
  }
}

export class WebrpcInternalErrorError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcInternalError'
    this.code = typeof error.code === 'number' ? error.code : -7
    this.message = error.message || `internal error`
    this.status = typeof error.status === 'number' ? error.status : 500
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcInternalErrorError.prototype)
  }
}

export class WebrpcClientAbortedError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcClientAborted'
    this.code = typeof error.code === 'number' ? error.code : -8
    this.message = error.message || `request aborted by client`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcClientAbortedError.prototype)
  }
}

export class WebrpcStreamLostError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcStreamLost'
    this.code = typeof error.code === 'number' ? error.code : -9
    this.message = error.message || `stream lost`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcStreamLostError.prototype)
  }
}

export class WebrpcStreamFinishedError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcStreamFinished'
    this.code = typeof error.code === 'number' ? error.code : -10
    this.message = error.message || `stream finished`
    this.status = typeof error.status === 'number' ? error.status : 200
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcStreamFinishedError.prototype)
  }
}


//
// Schema errors
//

export class UnauthorizedError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'Unauthorized'
    this.code = typeof error.code === 'number' ? error.code : 1
    this.message = error.message || `unauthorized`
    this.status = typeof error.status === 'number' ? error.status : 401
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, UnauthorizedError.prototype)
  }
}

export class ExpiredTokenError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'ExpiredToken'
    this.code = typeof error.code === 'number' ? error.code : 2
    this.message = error.message || `expired token`
    this.status = typeof error.status === 'number' ? error.status : 401
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, ExpiredTokenError.prototype)
  }
}

export class InvalidTokenError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'InvalidToken'
    this.code = typeof error.code === 'number' ? error.code : 3
    this.message = error.message || `invalid token`
    this.status = typeof error.status === 'number' ? error.status : 401
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, InvalidTokenError.prototype)
  }
}

export class DeactivatedError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'Deactivated'
    this.code = typeof error.code === 'number' ? error.code : 4
    this.message = error.message || `account deactivated`
    this.status = typeof error.status === 'number' ? error.status : 403
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, DeactivatedError.prototype)
  }
}

export class ConfirmAccountError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'ConfirmAccount'
    this.code = typeof error.code === 'number' ? error.code : 5
    this.message = error.message || `confirm your email`
    this.status = typeof error.status === 'number' ? error.status : 403
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, ConfirmAccountError.prototype)
  }
}

export class AccessDeniedError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'AccessDenied'
    this.code = typeof error.code === 'number' ? error.code : 6
    this.message = error.message || `access denied`
    this.status = typeof error.status === 'number' ? error.status : 403
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, AccessDeniedError.prototype)
  }
}

export class MissingArgumentError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'MissingArgument'
    this.code = typeof error.code === 'number' ? error.code : 7
    this.message = error.message || `missing argument`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, MissingArgumentError.prototype)
  }
}

export class UnexpectedValueError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'UnexpectedValue'
    this.code = typeof error.code === 'number' ? error.code : 8
    this.message = error.message || `unexpected value`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, UnexpectedValueError.prototype)
  }
}

export class RateLimitedError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'RateLimited'
    this.code = typeof error.code === 'number' ? error.code : 100
    this.message = error.message || `too many requests`
    this.status = typeof error.status === 'number' ? error.status : 429
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, RateLimitedError.prototype)
  }
}

export class DatabaseDownError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'DatabaseDown'
    this.code = typeof error.code === 'number' ? error.code : 101
    this.message = error.message || `service outage`
    this.status = typeof error.status === 'number' ? error.status : 503
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, DatabaseDownError.prototype)
  }
}

export class ElasticDownError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'ElasticDown'
    this.code = typeof error.code === 'number' ? error.code : 102
    this.message = error.message || `search is degraded`
    this.status = typeof error.status === 'number' ? error.status : 503
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, ElasticDownError.prototype)
  }
}

export class NotImplementedError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'NotImplemented'
    this.code = typeof error.code === 'number' ? error.code : 103
    this.message = error.message || `not implemented`
    this.status = typeof error.status === 'number' ? error.status : 501
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, NotImplementedError.prototype)
  }
}

export class UserNotFoundError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'UserNotFound'
    this.code = typeof error.code === 'number' ? error.code : 200
    this.message = error.message || `user not found`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, UserNotFoundError.prototype)
  }
}

export class UserBusyError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'UserBusy'
    this.code = typeof error.code === 'number' ? error.code : 201
    this.message = error.message || `user busy`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, UserBusyError.prototype)
  }
}

export class InvalidUsernameError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'InvalidUsername'
    this.code = typeof error.code === 'number' ? error.code : 202
    this.message = error.message || `invalid username`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, InvalidUsernameError.prototype)
  }
}

export class FileTooBigError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'FileTooBig'
    this.code = typeof error.code === 'number' ? error.code : 300
    this.message = error.message || `file is too big (max 1GB)`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, FileTooBigError.prototype)
  }
}

export class FileInfectedError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'FileInfected'
    this.code = typeof error.code === 'number' ? error.code : 301
    this.message = error.message || `file is infected`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, FileInfectedError.prototype)
  }
}

export class FileTypeError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'FileType'
    this.code = typeof error.code === 'number' ? error.code : 302
    this.message = error.message || `unsupported file type`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, FileTypeError.prototype)
  }
}

export enum errors {
  WebrpcEndpoint = 'WebrpcEndpoint',
  WebrpcRequestFailed = 'WebrpcRequestFailed',
  WebrpcBadRoute = 'WebrpcBadRoute',
  WebrpcBadMethod = 'WebrpcBadMethod',
  WebrpcBadRequest = 'WebrpcBadRequest',
  WebrpcBadResponse = 'WebrpcBadResponse',
  WebrpcServerPanic = 'WebrpcServerPanic',
  WebrpcInternalError = 'WebrpcInternalError',
  WebrpcClientAborted = 'WebrpcClientAborted',
  WebrpcStreamLost = 'WebrpcStreamLost',
  WebrpcStreamFinished = 'WebrpcStreamFinished',
  Unauthorized = 'Unauthorized',
  ExpiredToken = 'ExpiredToken',
  InvalidToken = 'InvalidToken',
  Deactivated = 'Deactivated',
  ConfirmAccount = 'ConfirmAccount',
  AccessDenied = 'AccessDenied',
  MissingArgument = 'MissingArgument',
  UnexpectedValue = 'UnexpectedValue',
  RateLimited = 'RateLimited',
  DatabaseDown = 'DatabaseDown',
  ElasticDown = 'ElasticDown',
  NotImplemented = 'NotImplemented',
  UserNotFound = 'UserNotFound',
  UserBusy = 'UserBusy',
  InvalidUsername = 'InvalidUsername',
  FileTooBig = 'FileTooBig',
  FileInfected = 'FileInfected',
  FileType = 'FileType',
}

export enum WebrpcErrorCodes {
  WebrpcEndpoint = 0,
  WebrpcRequestFailed = -1,
  WebrpcBadRoute = -2,
  WebrpcBadMethod = -3,
  WebrpcBadRequest = -4,
  WebrpcBadResponse = -5,
  WebrpcServerPanic = -6,
  WebrpcInternalError = -7,
  WebrpcClientAborted = -8,
  WebrpcStreamLost = -9,
  WebrpcStreamFinished = -10,
  Unauthorized = 1,
  ExpiredToken = 2,
  InvalidToken = 3,
  Deactivated = 4,
  ConfirmAccount = 5,
  AccessDenied = 6,
  MissingArgument = 7,
  UnexpectedValue = 8,
  RateLimited = 100,
  DatabaseDown = 101,
  ElasticDown = 102,
  NotImplemented = 103,
  UserNotFound = 200,
  UserBusy = 201,
  InvalidUsername = 202,
  FileTooBig = 300,
  FileInfected = 301,
  FileType = 302,
}

export const webrpcErrorByCode: { [code: number]: any } = {
  [0]: WebrpcEndpointError,
  [-1]: WebrpcRequestFailedError,
  [-2]: WebrpcBadRouteError,
  [-3]: WebrpcBadMethodError,
  [-4]: WebrpcBadRequestError,
  [-5]: WebrpcBadResponseError,
  [-6]: WebrpcServerPanicError,
  [-7]: WebrpcInternalErrorError,
  [-8]: WebrpcClientAbortedError,
  [-9]: WebrpcStreamLostError,
  [-10]: WebrpcStreamFinishedError,
  [1]: UnauthorizedError,
  [2]: ExpiredTokenError,
  [3]: InvalidTokenError,
  [4]: DeactivatedError,
  [5]: ConfirmAccountError,
  [6]: AccessDeniedError,
  [7]: MissingArgumentError,
  [8]: UnexpectedValueError,
  [100]: RateLimitedError,
  [101]: DatabaseDownError,
  [102]: ElasticDownError,
  [103]: NotImplementedError,
  [200]: UserNotFoundError,
  [201]: UserBusyError,
  [202]: InvalidUsernameError,
  [300]: FileTooBigError,
  [301]: FileInfectedError,
  [302]: FileTypeError,
}



//
// Webrpc
//

export const WebrpcHeader = "Webrpc"

export const WebrpcHeaderValue = "webrpc;typescript;Test@v1.0.0"

type WebrpcGenVersions = {
  WebrpcGenVersion: string;
  codeGenName: string;
  codeGenVersion: string;
  schemaName: string;
  schemaVersion: string;
};

export function VersionFromHeader(headers: Headers): WebrpcGenVersions {
  const headerValue = headers.get(WebrpcHeader)
  if (!headerValue) {
    return {
      WebrpcGenVersion: "",
      codeGenName: "",
      codeGenVersion: "",
      schemaName: "",
      schemaVersion: "",
    };
  }

  return parseWebrpcGenVersions(headerValue)
}

function parseWebrpcGenVersions(header: string): WebrpcGenVersions {
  const versions = header.split(";")
  if (versions.length < 3) {
    return {
      WebrpcGenVersion: "",
      codeGenName: "",
      codeGenVersion: "",
      schemaName: "",
      schemaVersion: "",
    };
  }

  const [_, WebrpcGenVersion] = versions[0]!.split("@")
  const [codeGenName, codeGenVersion] = versions[1]!.split("@")
  const [schemaName, schemaVersion] = versions[2]!.split("@")

  return {
    WebrpcGenVersion: WebrpcGenVersion ?? "",
    codeGenName: codeGenName ?? "",
    codeGenVersion: codeGenVersion ?? "",
    schemaName: schemaName ?? "",
    schemaVersion: schemaVersion ?? "",
  };
}

