/* eslint-disable */
// Test v1.0.0 95498be344c43f13a61e87c8fa2a6cc9d2d7df7c
// --
// Code generated by Webrpc-gen with typescript generator. DO NOT EDIT.
//
// webrpc-gen -schema=../schema/test.ridl -target=typescript -server -service=TestApiRest -out=./restServer.gen.ts
// Webrpc description and code-gen version
export const WebrpcVersion = "v1"

// Schema version of your RIDL schema
export const WebrpcSchemaVersion = "v1.0.0"

// Schema hash generated from your RIDL schema
export const WebrpcSchemaHash = "95498be344c43f13a61e87c8fa2a6cc9d2d7df7c"


//
// Server interface
//

export interface TestApiRestServer<Context = unknown> {
  getItem(ctx: Context, req: GetItemRequest): Promise<GetItemResponse>
  listItems(ctx: Context, req: ListItemsRequest): Promise<ListItemsResponse>
  createItem(ctx: Context, req: CreateItemRequest): Promise<CreateItemResponse>
  updateItem(ctx: Context, req: UpdateItemRequest): Promise<UpdateItemResponse>
  patchItem(ctx: Context, req: PatchItemRequest): Promise<PatchItemResponse>
  deleteItem(ctx: Context, req: DeleteItemRequest): Promise<DeleteItemResponse>
  queryItems(ctx: Context, req: QueryItemsRequest): Promise<QueryItemsResponse>
  echoParams(ctx: Context, req: EchoParamsRequest): Promise<EchoParamsResponse>
  getChild(ctx: Context, req: GetChildRequest): Promise<GetChildResponse>
  resetItems(ctx: Context, req: ResetItemsRequest): Promise<ResetItemsResponse>
  rpcMethod(ctx: Context, req: RpcMethodRequest): Promise<RpcMethodResponse>
}

//
// Schema types
//

export enum Status {
  AVAILABLE = 'AVAILABLE',
  NOT_AVAILABLE = 'NOT_AVAILABLE'
}

export enum Access {
  NONE = 'NONE',
  READ = 'READ',
  WRITE = 'WRITE',
  ADMIN = 'ADMIN',
  OWNER = 'OWNER'
}

export interface Item {
  id: number
  name: string
}

export interface GetItemRequest {
  id: number
  details?: boolean
}

export interface GetItemResponse {
  item: Item
}

export interface ListItemsRequest {
  q?: string
  tags: Array<string>
  limit: number
}

export interface ListItemsResponse {
  items: Array<Item>
}

export interface CreateItemRequest {
  item: Item
}

export interface CreateItemResponse {
  item: Item
}

export interface Simple {
  id: number
  name: string
}

export interface User {
  id: number
  USERNAME: string
  role: string
}

export interface Complex {
  meta: {[key: string]: any}
  metaNestedExample: {[key: string]: {[key: string]: number}}
  namesList: Array<string>
  numsList: Array<number>
  doubleArray: Array<Array<string>>
  listOfMaps: Array<{[key: string]: number}>
  listOfUsers: Array<User>
  mapOfUsers: {[key: string]: User}
  user: User
  status: Status
}

export interface EnumData {
  dict: {[key in Access]?: number}
  list: Array<Status>
}




export interface UpdateItemRequest {
  id: number
  name: string
}

export interface UpdateItemResponse {
  item: Item
}

export interface PatchItemRequest {
  id: number
  name?: string
}

export interface PatchItemResponse {
  item: Item
}

export interface DeleteItemRequest {
  id: number
}

export interface DeleteItemResponse {
}

export interface QueryItemsRequest {
  q: string
}

export interface QueryItemsResponse {
  items: Array<Item>
}

export interface EchoParamsRequest {
  str: string
  num: number
  flag: boolean
  fl: number
  ts: string
  status: Status
  tags: Array<string>
  opt?: string
}

export interface EchoParamsResponse {
  echo: string
}

export interface GetChildRequest {
  id: number
  childId: number
}

export interface GetChildResponse {
  path: string
}

export interface ResetItemsRequest {
}

export interface ResetItemsResponse {
}

export interface RpcMethodRequest {
  id: number
}

export interface RpcMethodResponse {
  item: Item
}




//
// Server handler
//

// serveTestApiRestRpc dispatches a web-standard Request to the TestApiRest service
// and returns a web-standard Response, or null when the request path does not
// belong to this service (so the caller can try other routes).
export const serveTestApiRestRpc = async <Context>(service: TestApiRestServer<Context>, ctx: Context, request: Request): Promise<Response | null> => {
  const rest = await webrpcRestToRpcRequest(testApiRestRestRoutes, request)
  if (rest instanceof Response) return rest
  if (rest) request = rest
  const pathname = new URL(request.url).pathname
  if (!pathname.startsWith('/rpc/TestApiRest/')) return null
  const method = pathname.slice('/rpc/TestApiRest/'.length)
  if (method === '' || method.includes('/')) return null

  if (request.method !== 'POST') {
    return webrpcErrorResponse(new WebrpcBadMethodError({ cause: `unsupported HTTP method ${request.method} (only POST is allowed)` }), { Allow: 'POST' })
  }

  try {
    return await dispatchTestApiRestRequest(service, ctx, method, request)
  } catch (err) {
    return webrpcErrorResponse(err)
  }
}

const testApiRestRestRoutes: WebrpcRestRoute[] = [
  { method: 'GET', path: '/rpc/items/{id}', rpcPath: '/rpc/TestApiRest/GetItem', params: ['id: uint64', 'details?: bool'] },
  { method: 'GET', path: '/rpc/items', rpcPath: '/rpc/TestApiRest/ListItems', params: ['q?: string', 'tags: []string', 'limit: uint32'] },
  { method: 'POST', path: '/rpc/items', rpcPath: '/rpc/TestApiRest/CreateItem', params: [] },
  { method: 'PUT', path: '/rpc/items/{id}', rpcPath: '/rpc/TestApiRest/UpdateItem', params: ['id: uint64'] },
  { method: 'PATCH', path: '/rpc/items/{id}', rpcPath: '/rpc/TestApiRest/PatchItem', params: ['id: uint64'] },
  { method: 'DELETE', path: '/rpc/items/{id}', rpcPath: '/rpc/TestApiRest/DeleteItem', params: ['id: uint64'] },
  { method: 'QUERY', path: '/rpc/items/search', rpcPath: '/rpc/TestApiRest/QueryItems', params: ['q: string'] },
  { method: 'GET', path: '/rpc/items/echo/params', rpcPath: '/rpc/TestApiRest/EchoParams', params: ['str: string', 'num: int64', 'flag: bool', 'fl: float64', 'ts: timestamp', 'status: Status', 'tags: []string', 'opt?: string'] },
  { method: 'GET', path: '/rpc/items/{id}/children/{childId}', rpcPath: '/rpc/TestApiRest/GetChild', params: ['id: uint64', 'childId: uint64'] },
  { method: 'POST', path: '/rpc/items/reset', rpcPath: '/rpc/TestApiRest/ResetItems', params: [] },
]

const dispatchTestApiRestRequest = async <Context>(service: TestApiRestServer<Context>, ctx: Context, method: string, request: Request): Promise<Response> => {
  switch (method) {
    case 'GetItem': {
      const payload: any = webrpcParseRequestBody(await webrpcRequestBodyText(request), 'GetItemRequest')
      if (payload && !validateType(payload, "GetItemRequest")) {
        throw new WebrpcBadRequestError({ cause: "invalid argument: getItemRequest" })
      }
      const result = await service.getItem(ctx, payload || {})
      return webrpcJsonResponse(result ?? {})
    }
  
    case 'ListItems': {
      const payload: any = webrpcParseRequestBody(await webrpcRequestBodyText(request), 'ListItemsRequest')
      if (payload && !validateType(payload, "ListItemsRequest")) {
        throw new WebrpcBadRequestError({ cause: "invalid argument: listItemsRequest" })
      }
      const result = await service.listItems(ctx, payload || {})
      return webrpcJsonResponse(result ?? {})
    }
  
    case 'CreateItem': {
      const payload: any = webrpcParseRequestBody(await webrpcRequestBodyText(request), 'CreateItemRequest')
      if (payload && !validateType(payload, "CreateItemRequest")) {
        throw new WebrpcBadRequestError({ cause: "invalid argument: createItemRequest" })
      }
      const result = await service.createItem(ctx, payload || {})
      return webrpcJsonResponse(result ?? {})
    }
  
    case 'UpdateItem': {
      const payload: any = webrpcParseRequestBody(await webrpcRequestBodyText(request), 'UpdateItemRequest')
      if (!("id" in payload)) {
        throw new WebrpcBadRequestError({ cause: "missing argument `id`" })
      }
      if ("id" in payload && !validateType(payload["id"], "number")) {
        throw new WebrpcBadRequestError({ cause: "invalid argument: id" })
      }
      if (!("name" in payload)) {
        throw new WebrpcBadRequestError({ cause: "missing argument `name`" })
      }
      if ("name" in payload && !validateType(payload["name"], "string")) {
        throw new WebrpcBadRequestError({ cause: "invalid argument: name" })
      }
      const result = await service.updateItem(ctx, payload || {})
      return webrpcJsonResponse(result ?? {})
    }
  
    case 'PatchItem': {
      const payload: any = webrpcParseRequestBody(await webrpcRequestBodyText(request), 'PatchItemRequest')
      if (!("id" in payload)) {
        throw new WebrpcBadRequestError({ cause: "missing argument `id`" })
      }
      if ("id" in payload && !validateType(payload["id"], "number")) {
        throw new WebrpcBadRequestError({ cause: "invalid argument: id" })
      }
      if ("name" in payload && !validateType(payload["name"], "string")) {
        throw new WebrpcBadRequestError({ cause: "invalid argument: name" })
      }
      const result = await service.patchItem(ctx, payload || {})
      return webrpcJsonResponse(result ?? {})
    }
  
    case 'DeleteItem': {
      const payload: any = webrpcParseRequestBody(await webrpcRequestBodyText(request), 'DeleteItemRequest')
      if (!("id" in payload)) {
        throw new WebrpcBadRequestError({ cause: "missing argument `id`" })
      }
      if ("id" in payload && !validateType(payload["id"], "number")) {
        throw new WebrpcBadRequestError({ cause: "invalid argument: id" })
      }
      const result = await service.deleteItem(ctx, payload || {})
      return webrpcJsonResponse(result ?? {})
    }
  
    case 'QueryItems': {
      const payload: any = webrpcParseRequestBody(await webrpcRequestBodyText(request), 'QueryItemsRequest')
      if (!("q" in payload)) {
        throw new WebrpcBadRequestError({ cause: "missing argument `q`" })
      }
      if ("q" in payload && !validateType(payload["q"], "string")) {
        throw new WebrpcBadRequestError({ cause: "invalid argument: q" })
      }
      const result = await service.queryItems(ctx, payload || {})
      return webrpcJsonResponse(result ?? {})
    }
  
    case 'EchoParams': {
      const payload: any = webrpcParseRequestBody(await webrpcRequestBodyText(request), 'EchoParamsRequest')
      if (!("str" in payload)) {
        throw new WebrpcBadRequestError({ cause: "missing argument `str`" })
      }
      if ("str" in payload && !validateType(payload["str"], "string")) {
        throw new WebrpcBadRequestError({ cause: "invalid argument: str" })
      }
      if (!("num" in payload)) {
        throw new WebrpcBadRequestError({ cause: "missing argument `num`" })
      }
      if ("num" in payload && !validateType(payload["num"], "number")) {
        throw new WebrpcBadRequestError({ cause: "invalid argument: num" })
      }
      if (!("flag" in payload)) {
        throw new WebrpcBadRequestError({ cause: "missing argument `flag`" })
      }
      if ("flag" in payload && !validateType(payload["flag"], "boolean")) {
        throw new WebrpcBadRequestError({ cause: "invalid argument: flag" })
      }
      if (!("fl" in payload)) {
        throw new WebrpcBadRequestError({ cause: "missing argument `fl`" })
      }
      if ("fl" in payload && !validateType(payload["fl"], "number")) {
        throw new WebrpcBadRequestError({ cause: "invalid argument: fl" })
      }
      if (!("ts" in payload)) {
        throw new WebrpcBadRequestError({ cause: "missing argument `ts`" })
      }
      if ("ts" in payload && !validateType(payload["ts"], "string")) {
        throw new WebrpcBadRequestError({ cause: "invalid argument: ts" })
      }
      if (!("status" in payload)) {
        throw new WebrpcBadRequestError({ cause: "missing argument `status`" })
      }
      if ("status" in payload && !validateType(payload["status"], "Status")) {
        throw new WebrpcBadRequestError({ cause: "invalid argument: status" })
      }
      if (!("tags" in payload)) {
        throw new WebrpcBadRequestError({ cause: "missing argument `tags`" })
      }
      if ("tags" in payload && !validateType(payload["tags"], "string[]")) {
        throw new WebrpcBadRequestError({ cause: "invalid argument: tags" })
      }
      if ("opt" in payload && !validateType(payload["opt"], "string")) {
        throw new WebrpcBadRequestError({ cause: "invalid argument: opt" })
      }
      const result = await service.echoParams(ctx, payload || {})
      return webrpcJsonResponse(result ?? {})
    }
  
    case 'GetChild': {
      const payload: any = webrpcParseRequestBody(await webrpcRequestBodyText(request), 'GetChildRequest')
      if (!("id" in payload)) {
        throw new WebrpcBadRequestError({ cause: "missing argument `id`" })
      }
      if ("id" in payload && !validateType(payload["id"], "number")) {
        throw new WebrpcBadRequestError({ cause: "invalid argument: id" })
      }
      if (!("childId" in payload)) {
        throw new WebrpcBadRequestError({ cause: "missing argument `childId`" })
      }
      if ("childId" in payload && !validateType(payload["childId"], "number")) {
        throw new WebrpcBadRequestError({ cause: "invalid argument: childId" })
      }
      const result = await service.getChild(ctx, payload || {})
      return webrpcJsonResponse(result ?? {})
    }
  
    case 'ResetItems': {
      const payload: any = webrpcParseRequestBody(await webrpcRequestBodyText(request), 'ResetItemsRequest')
      const result = await service.resetItems(ctx, payload || {})
      return webrpcJsonResponse(result ?? {})
    }
  
    case 'RpcMethod': {
      const payload: any = webrpcParseRequestBody(await webrpcRequestBodyText(request), 'RpcMethodRequest')
      if (!("id" in payload)) {
        throw new WebrpcBadRequestError({ cause: "missing argument `id`" })
      }
      if ("id" in payload && !validateType(payload["id"], "number")) {
        throw new WebrpcBadRequestError({ cause: "invalid argument: id" })
      }
      const result = await service.rpcMethod(ctx, payload || {})
      return webrpcJsonResponse(result ?? {})
    }
  
    default:
      throw new WebrpcBadRouteError({ cause: 'method not found' })
  }
}


const webrpcRequestBodyText = async (request: Request): Promise<string> => {
  const contentType = (request.headers.get('Content-Type') || '').split(';')[0]!.trim().toLowerCase()
  if (contentType !== 'application/json') {
    throw new WebrpcBadRequestError({ cause: `unsupported Content-Type '${request.headers.get('Content-Type') || ''}' (only application/json is allowed)` })
  }
  return request.text()
}

const webrpcParseRequestBody = (body: unknown, typ: string): any => {
  if (typeof body !== 'string' || body === '') {
    return {}
  }
  let data: any
  try {
    data = JSON.parse(body)
  } catch (err) {
    throw new WebrpcBadRequestError({ cause: `failed to unmarshal request data: ${err instanceof Error ? err.message : String(err)}` })
  }
  try {
    return JsonDecode(data, typ) ?? {}
  } catch (err) {
    throw new WebrpcBadRequestError({ cause: `failed to unmarshal request data: ${err instanceof WebrpcError ? String(err.cause ?? err.message) : err instanceof Error ? err.message : String(err)}` })
  }
}

const webrpcJsonResponse = (data: any): Response => {
  return new Response(JsonEncode(data), {
    status: 200,
    headers: { [WebrpcHeader]: WebrpcHeaderValue, 'Content-Type': 'application/json' },
  })
}

const webrpcErrorResponse = (err: unknown, headers?: { [key: string]: string }): Response => {
  const rpcErr = err instanceof WebrpcError ? err : new WebrpcEndpointError({ cause: err instanceof Error ? err.message : String(err) })
  const body: { [key: string]: any } = { error: rpcErr.name, code: rpcErr.code, msg: rpcErr.message, status: rpcErr.status }
  if (rpcErr.cause !== undefined) {
    body['cause'] = String(rpcErr.cause)
  }
  return new Response(JSON.stringify(body), {
    status: rpcErr.status || 400,
    headers: { ...headers, [WebrpcHeader]: WebrpcHeaderValue, 'Content-Type': 'application/json' },
  })
}


// WebrpcRestRoute serves a REST route as the webrpc method at rpcPath. Params
// bind path and query params to request fields, in RIDL syntax: 'tags?: []string'.
type WebrpcRestRoute = { method: string, path: string, rpcPath: string, params: string[] }

// webrpcRestToRpcRequest rewrites a REST route request into its webrpc method
// request: POST rpcPath with path and query params merged into the JSON body.
// Returns null when no route path matches, or an error Response.
const webrpcRestToRpcRequest = async (routes: WebrpcRestRoute[], request: Request): Promise<Request | Response | null> => {
  const url = new URL(request.url)
  // A routed method answers only on its route.
  if (routes.some((route) => route.rpcPath === url.pathname)) {
    return webrpcErrorResponse(new WebrpcBadRouteError({ cause: `no webrpc method defined for path ${url.pathname}` }))
  }
  const segments = url.pathname.split('/').filter((s) => s !== '')
  const allowed: string[] = []
  let match: { route: WebrpcRestRoute, pathParams: { [name: string]: string }, static: number } | undefined
  for (const route of routes) {
    const pathParams = webrpcMatchRestPath(route.path, segments)
    if (!pathParams) continue
    allowed.push(route.method)
    // Static segments beat params, e.g. /items/search over /items/{id}.
    const staticCount = segments.length - Object.keys(pathParams).length
    if (route.method === request.method && (!match || staticCount > match.static)) {
      match = { route, pathParams, static: staticCount }
    }
  }
  if (!match) {
    return allowed.length === 0 ? null : webrpcErrorResponse(new WebrpcBadMethodError({ cause: `unsupported HTTP method ${request.method} (allowed: ${allowed.join(', ')})` }), { Allow: allowed.join(', ') })
  }

  try {
    const { route, pathParams } = match
    const hasBody = route.method === 'POST' || route.method === 'PUT' || route.method === 'PATCH'
    const payload: any = hasBody ? webrpcParseRequestBody(await webrpcRequestBodyText(request), '') : {}
    for (const param of route.params) {
      const [, name, optional, repeated, type] = param.match(/^(\w+)(\??): (\[\])?(\w+)$/)!
      const kind = name! in pathParams ? 'path' : 'query'
      const values = kind === 'path' ? [pathParams[name!]!] : url.searchParams.getAll(name!)
      if (values.length === 0) {
        if (repeated && !optional) payload[name!] = []
        else if (!optional) throw new WebrpcBadRequestError({ cause: `missing ${kind} param '${name}'` })
        continue
      }
      const coerced = values.map((v) => {
        const value = webrpcRestParam(v, type!)
        if (value === undefined) throw new WebrpcBadRequestError({ cause: `invalid ${kind} param '${name}': "${v}" is not a valid ${type}` })
        return value
      })
      payload[name!] = repeated ? coerced : coerced[0]
    }

    const headers = new Headers(request.headers)
    headers.set('Content-Type', 'application/json')
    return new Request(new URL(route.rpcPath, url), { method: 'POST', headers, body: JSON.stringify(payload) })
  } catch (err) {
    return webrpcErrorResponse(err)
  }
}

// webrpcMatchRestPath returns the decoded path params if segments match the path template.
const webrpcMatchRestPath = (path: string, segments: string[]): { [name: string]: string } | null => {
  const parts = path.split('/').filter((s) => s !== '')
  if (parts.length !== segments.length) return null
  const params: { [name: string]: string } = {}
  for (let i = 0; i < parts.length; i++) {
    const part = parts[i]!
    if (!part.startsWith('{')) {
      if (part !== segments[i]) return null
      continue
    }
    try {
      params[part.slice(1, -1)] = decodeURIComponent(segments[i]!)
    } catch {
      return null
    }
  }
  return params
}

// webrpcRestParam converts a path/query param string to the field's type, or undefined if invalid.
const webrpcRestParam = (value: string, type: string): any => {
  if (type === 'bool') {
    return value === 'true' ? true : value === 'false' ? false : undefined
  }
  if (/^u?int/.test(type)) {
    return (type.startsWith('u') ? /^\d+$/ : /^-?\d+$/).test(value) ? Number(value) : undefined
  }
  if (type.startsWith('float')) {
    const n = Number(value)
    return value.trim() !== '' && Number.isFinite(n) ? n : undefined
  }
  return value
}



//
// Server type validators
//

const JS_TYPES = [
    "bigint",
    "boolean",
    "function",
    "number",
    "object",
    "string",
    "symbol",
    "undefined"
]

const validateStatus = (value: any): boolean => {
  return value === 'AVAILABLE' || value === 'NOT_AVAILABLE'
}

const validateAccess = (value: any): boolean => {
  return value === 'NONE' || value === 'READ' || value === 'WRITE' || value === 'ADMIN' || value === 'OWNER'
}

const validateItem = (value: any) => {
  if (!("id" in value) || !validateType(value["id"], "number")) {
    return false
  }
  if (!("name" in value) || !validateType(value["name"], "string")) {
    return false
  }
  return true
}

const validateGetItemRequest = (value: any) => {
  if (!("id" in value) || !validateType(value["id"], "number")) {
    return false
  }
  if ("details" in value && !validateType(value["details"], "boolean")) {
    return false
  }
  return true
}

const validateGetItemResponse = (value: any) => {
  if (!("item" in value) || !validateType(value["item"], "Item")) {
    return false
  }
  return true
}

const validateListItemsRequest = (value: any) => {
  if ("q" in value && !validateType(value["q"], "string")) {
    return false
  }
  if (!("tags" in value) || !validateType(value["tags"], "string[]")) {
    return false
  }
  if (!("limit" in value) || !validateType(value["limit"], "number")) {
    return false
  }
  return true
}

const validateListItemsResponse = (value: any) => {
  if (!("items" in value) || !validateType(value["items"], "Item[]")) {
    return false
  }
  return true
}

const validateCreateItemRequest = (value: any) => {
  if (!("item" in value) || !validateType(value["item"], "Item")) {
    return false
  }
  return true
}

const validateCreateItemResponse = (value: any) => {
  if (!("item" in value) || !validateType(value["item"], "Item")) {
    return false
  }
  return true
}

const validateSimple = (value: any) => {
  if (!("id" in value) || !validateType(value["id"], "number")) {
    return false
  }
  if (!("name" in value) || !validateType(value["name"], "string")) {
    return false
  }
  return true
}

const validateUser = (value: any) => {
  if (!("id" in value) || !validateType(value["id"], "number")) {
    return false
  }
  if (!("USERNAME" in value) || !validateType(value["USERNAME"], "string")) {
    return false
  }
  if (!("role" in value) || !validateType(value["role"], "string")) {
    return false
  }
  return true
}

const validateComplex = (value: any) => {
  if (!("meta" in value) || !validateType(value["meta"], "object")) {
    return false
  }
  if (!("metaNestedExample" in value) || !validateType(value["metaNestedExample"], "object")) {
    return false
  }
  if (!("namesList" in value) || !validateType(value["namesList"], "string[]")) {
    return false
  }
  if (!("numsList" in value) || !validateType(value["numsList"], "number[]")) {
    return false
  }
  if (!("doubleArray" in value) || !validateType(value["doubleArray"], "string[][]")) {
    return false
  }
  if (!("listOfMaps" in value) || !validateType(value["listOfMaps"], "object[]")) {
    return false
  }
  if (!("listOfUsers" in value) || !validateType(value["listOfUsers"], "User[]")) {
    return false
  }
  if (!("mapOfUsers" in value) || !validateType(value["mapOfUsers"], "object")) {
    return false
  }
  if (!("user" in value) || !validateType(value["user"], "User")) {
    return false
  }
  if (!("status" in value) || !validateType(value["status"], "Status")) {
    return false
  }
  return true
}

const validateEnumData = (value: any) => {
  if (!("dict" in value) || !validateType(value["dict"], "object")) {
    return false
  }
  if (!("list" in value) || !validateType(value["list"], "Status[]")) {
    return false
  }
  return true
}

const TYPE_VALIDATORS: { [type: string]: (value: any) => boolean } = {
  Status: validateStatus,
  Access: validateAccess,
  Item: validateItem,
  GetItemRequest: validateGetItemRequest,
  GetItemResponse: validateGetItemResponse,
  ListItemsRequest: validateListItemsRequest,
  ListItemsResponse: validateListItemsResponse,
  CreateItemRequest: validateCreateItemRequest,
  CreateItemResponse: validateCreateItemResponse,
  Simple: validateSimple,
  User: validateUser,
  Complex: validateComplex,
  EnumData: validateEnumData,
}

const validateType = (value: any, type: string): boolean => {
  if (type === "any") {
    return true;
  }
  if (type.endsWith("[]")) {
    const elemType = type.slice(0, -2);
    return Array.isArray(value) && value.every((elem) => validateType(elem, elemType));
  }
  if (JS_TYPES.indexOf(type) > -1) {
    return typeof value === type;
  }
  const validator = TYPE_VALIDATORS[type];
  if (!validator) {
    return false;
  }
  return validator(value)
}


export const JsonEncode = <T = any>(obj: T): string => {
  return JSON.stringify(obj)
}

export const JsonDecode = <T = any>(data: string | any, _typ: string = ''): T => {
  let parsed: any = data
  if (typeof data === 'string') {
    try { parsed = JSON.parse(data) } catch (err) {
      throw WebrpcBadResponseError.new({ cause: `JsonDecode: JSON.parse failed: ${(err as Error).message}` })
    }
  }
  return parsed as T
}


//
// Errors
//

type WebrpcErrorParams = { name?: string, code?: number, message?: string, status?: number, cause?: string }

export class WebrpcError extends Error {
  code: number
  status: number

  constructor(error: WebrpcErrorParams = {}) {
    super(error.message)
    this.name = error.name || 'WebrpcEndpointError'
    this.code = typeof error.code === 'number' ? error.code : 0
    this.message = error.message || `endpoint error`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcError.prototype)
  }

  static new(payload: any): WebrpcError {
    return new this({ message: payload.message, code: payload.code, status: payload.status, cause: payload.cause })
  }
}


export class WebrpcEndpointError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcEndpoint'
    this.code = typeof error.code === 'number' ? error.code : 0
    this.message = error.message || `endpoint error`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcEndpointError.prototype)
  }
}

export class WebrpcRequestFailedError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcRequestFailed'
    this.code = typeof error.code === 'number' ? error.code : -1
    this.message = error.message || `request failed`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcRequestFailedError.prototype)
  }
}

export class WebrpcBadRouteError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcBadRoute'
    this.code = typeof error.code === 'number' ? error.code : -2
    this.message = error.message || `bad route`
    this.status = typeof error.status === 'number' ? error.status : 404
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcBadRouteError.prototype)
  }
}

export class WebrpcBadMethodError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcBadMethod'
    this.code = typeof error.code === 'number' ? error.code : -3
    this.message = error.message || `bad method`
    this.status = typeof error.status === 'number' ? error.status : 405
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcBadMethodError.prototype)
  }
}

export class WebrpcBadRequestError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcBadRequest'
    this.code = typeof error.code === 'number' ? error.code : -4
    this.message = error.message || `bad request`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcBadRequestError.prototype)
  }
}

export class WebrpcBadResponseError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcBadResponse'
    this.code = typeof error.code === 'number' ? error.code : -5
    this.message = error.message || `bad response`
    this.status = typeof error.status === 'number' ? error.status : 500
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcBadResponseError.prototype)
  }
}

export class WebrpcServerPanicError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcServerPanic'
    this.code = typeof error.code === 'number' ? error.code : -6
    this.message = error.message || `server panic`
    this.status = typeof error.status === 'number' ? error.status : 500
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcServerPanicError.prototype)
  }
}

export class WebrpcInternalErrorError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcInternalError'
    this.code = typeof error.code === 'number' ? error.code : -7
    this.message = error.message || `internal error`
    this.status = typeof error.status === 'number' ? error.status : 500
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcInternalErrorError.prototype)
  }
}

export class WebrpcClientAbortedError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcClientAborted'
    this.code = typeof error.code === 'number' ? error.code : -8
    this.message = error.message || `request aborted by client`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcClientAbortedError.prototype)
  }
}

export class WebrpcStreamLostError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcStreamLost'
    this.code = typeof error.code === 'number' ? error.code : -9
    this.message = error.message || `stream lost`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcStreamLostError.prototype)
  }
}

export class WebrpcStreamFinishedError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcStreamFinished'
    this.code = typeof error.code === 'number' ? error.code : -10
    this.message = error.message || `stream finished`
    this.status = typeof error.status === 'number' ? error.status : 200
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcStreamFinishedError.prototype)
  }
}


//
// Schema errors
//

export class UnauthorizedError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'Unauthorized'
    this.code = typeof error.code === 'number' ? error.code : 1
    this.message = error.message || `unauthorized`
    this.status = typeof error.status === 'number' ? error.status : 401
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, UnauthorizedError.prototype)
  }
}

export class ExpiredTokenError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'ExpiredToken'
    this.code = typeof error.code === 'number' ? error.code : 2
    this.message = error.message || `expired token`
    this.status = typeof error.status === 'number' ? error.status : 401
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, ExpiredTokenError.prototype)
  }
}

export class InvalidTokenError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'InvalidToken'
    this.code = typeof error.code === 'number' ? error.code : 3
    this.message = error.message || `invalid token`
    this.status = typeof error.status === 'number' ? error.status : 401
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, InvalidTokenError.prototype)
  }
}

export class DeactivatedError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'Deactivated'
    this.code = typeof error.code === 'number' ? error.code : 4
    this.message = error.message || `account deactivated`
    this.status = typeof error.status === 'number' ? error.status : 403
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, DeactivatedError.prototype)
  }
}

export class ConfirmAccountError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'ConfirmAccount'
    this.code = typeof error.code === 'number' ? error.code : 5
    this.message = error.message || `confirm your email`
    this.status = typeof error.status === 'number' ? error.status : 403
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, ConfirmAccountError.prototype)
  }
}

export class AccessDeniedError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'AccessDenied'
    this.code = typeof error.code === 'number' ? error.code : 6
    this.message = error.message || `access denied`
    this.status = typeof error.status === 'number' ? error.status : 403
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, AccessDeniedError.prototype)
  }
}

export class MissingArgumentError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'MissingArgument'
    this.code = typeof error.code === 'number' ? error.code : 7
    this.message = error.message || `missing argument`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, MissingArgumentError.prototype)
  }
}

export class UnexpectedValueError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'UnexpectedValue'
    this.code = typeof error.code === 'number' ? error.code : 8
    this.message = error.message || `unexpected value`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, UnexpectedValueError.prototype)
  }
}

export class RateLimitedError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'RateLimited'
    this.code = typeof error.code === 'number' ? error.code : 100
    this.message = error.message || `too many requests`
    this.status = typeof error.status === 'number' ? error.status : 429
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, RateLimitedError.prototype)
  }
}

export class DatabaseDownError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'DatabaseDown'
    this.code = typeof error.code === 'number' ? error.code : 101
    this.message = error.message || `service outage`
    this.status = typeof error.status === 'number' ? error.status : 503
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, DatabaseDownError.prototype)
  }
}

export class ElasticDownError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'ElasticDown'
    this.code = typeof error.code === 'number' ? error.code : 102
    this.message = error.message || `search is degraded`
    this.status = typeof error.status === 'number' ? error.status : 503
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, ElasticDownError.prototype)
  }
}

export class NotImplementedError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'NotImplemented'
    this.code = typeof error.code === 'number' ? error.code : 103
    this.message = error.message || `not implemented`
    this.status = typeof error.status === 'number' ? error.status : 501
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, NotImplementedError.prototype)
  }
}

export class UserNotFoundError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'UserNotFound'
    this.code = typeof error.code === 'number' ? error.code : 200
    this.message = error.message || `user not found`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, UserNotFoundError.prototype)
  }
}

export class UserBusyError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'UserBusy'
    this.code = typeof error.code === 'number' ? error.code : 201
    this.message = error.message || `user busy`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, UserBusyError.prototype)
  }
}

export class InvalidUsernameError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'InvalidUsername'
    this.code = typeof error.code === 'number' ? error.code : 202
    this.message = error.message || `invalid username`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, InvalidUsernameError.prototype)
  }
}

export class FileTooBigError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'FileTooBig'
    this.code = typeof error.code === 'number' ? error.code : 300
    this.message = error.message || `file is too big (max 1GB)`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, FileTooBigError.prototype)
  }
}

export class FileInfectedError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'FileInfected'
    this.code = typeof error.code === 'number' ? error.code : 301
    this.message = error.message || `file is infected`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, FileInfectedError.prototype)
  }
}

export class FileTypeError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'FileType'
    this.code = typeof error.code === 'number' ? error.code : 302
    this.message = error.message || `unsupported file type`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, FileTypeError.prototype)
  }
}

export enum errors {
  WebrpcEndpoint = 'WebrpcEndpoint',
  WebrpcRequestFailed = 'WebrpcRequestFailed',
  WebrpcBadRoute = 'WebrpcBadRoute',
  WebrpcBadMethod = 'WebrpcBadMethod',
  WebrpcBadRequest = 'WebrpcBadRequest',
  WebrpcBadResponse = 'WebrpcBadResponse',
  WebrpcServerPanic = 'WebrpcServerPanic',
  WebrpcInternalError = 'WebrpcInternalError',
  WebrpcClientAborted = 'WebrpcClientAborted',
  WebrpcStreamLost = 'WebrpcStreamLost',
  WebrpcStreamFinished = 'WebrpcStreamFinished',
  Unauthorized = 'Unauthorized',
  ExpiredToken = 'ExpiredToken',
  InvalidToken = 'InvalidToken',
  Deactivated = 'Deactivated',
  ConfirmAccount = 'ConfirmAccount',
  AccessDenied = 'AccessDenied',
  MissingArgument = 'MissingArgument',
  UnexpectedValue = 'UnexpectedValue',
  RateLimited = 'RateLimited',
  DatabaseDown = 'DatabaseDown',
  ElasticDown = 'ElasticDown',
  NotImplemented = 'NotImplemented',
  UserNotFound = 'UserNotFound',
  UserBusy = 'UserBusy',
  InvalidUsername = 'InvalidUsername',
  FileTooBig = 'FileTooBig',
  FileInfected = 'FileInfected',
  FileType = 'FileType',
}

export enum WebrpcErrorCodes {
  WebrpcEndpoint = 0,
  WebrpcRequestFailed = -1,
  WebrpcBadRoute = -2,
  WebrpcBadMethod = -3,
  WebrpcBadRequest = -4,
  WebrpcBadResponse = -5,
  WebrpcServerPanic = -6,
  WebrpcInternalError = -7,
  WebrpcClientAborted = -8,
  WebrpcStreamLost = -9,
  WebrpcStreamFinished = -10,
  Unauthorized = 1,
  ExpiredToken = 2,
  InvalidToken = 3,
  Deactivated = 4,
  ConfirmAccount = 5,
  AccessDenied = 6,
  MissingArgument = 7,
  UnexpectedValue = 8,
  RateLimited = 100,
  DatabaseDown = 101,
  ElasticDown = 102,
  NotImplemented = 103,
  UserNotFound = 200,
  UserBusy = 201,
  InvalidUsername = 202,
  FileTooBig = 300,
  FileInfected = 301,
  FileType = 302,
}

export const webrpcErrorByCode: { [code: number]: any } = {
  [0]: WebrpcEndpointError,
  [-1]: WebrpcRequestFailedError,
  [-2]: WebrpcBadRouteError,
  [-3]: WebrpcBadMethodError,
  [-4]: WebrpcBadRequestError,
  [-5]: WebrpcBadResponseError,
  [-6]: WebrpcServerPanicError,
  [-7]: WebrpcInternalErrorError,
  [-8]: WebrpcClientAbortedError,
  [-9]: WebrpcStreamLostError,
  [-10]: WebrpcStreamFinishedError,
  [1]: UnauthorizedError,
  [2]: ExpiredTokenError,
  [3]: InvalidTokenError,
  [4]: DeactivatedError,
  [5]: ConfirmAccountError,
  [6]: AccessDeniedError,
  [7]: MissingArgumentError,
  [8]: UnexpectedValueError,
  [100]: RateLimitedError,
  [101]: DatabaseDownError,
  [102]: ElasticDownError,
  [103]: NotImplementedError,
  [200]: UserNotFoundError,
  [201]: UserBusyError,
  [202]: InvalidUsernameError,
  [300]: FileTooBigError,
  [301]: FileInfectedError,
  [302]: FileTypeError,
}



//
// Webrpc
//

export const WebrpcHeader = "Webrpc"

export const WebrpcHeaderValue = "webrpc;typescript;Test@v1.0.0"

type WebrpcGenVersions = {
  WebrpcGenVersion: string;
  codeGenName: string;
  codeGenVersion: string;
  schemaName: string;
  schemaVersion: string;
};

export function VersionFromHeader(headers: Headers): WebrpcGenVersions {
  const headerValue = headers.get(WebrpcHeader)
  if (!headerValue) {
    return {
      WebrpcGenVersion: "",
      codeGenName: "",
      codeGenVersion: "",
      schemaName: "",
      schemaVersion: "",
    };
  }

  return parseWebrpcGenVersions(headerValue)
}

function parseWebrpcGenVersions(header: string): WebrpcGenVersions {
  const versions = header.split(";")
  if (versions.length < 3) {
    return {
      WebrpcGenVersion: "",
      codeGenName: "",
      codeGenVersion: "",
      schemaName: "",
      schemaVersion: "",
    };
  }

  const [_, WebrpcGenVersion] = versions[0]!.split("@")
  const [codeGenName, codeGenVersion] = versions[1]!.split("@")
  const [schemaName, schemaVersion] = versions[2]!.split("@")

  return {
    WebrpcGenVersion: WebrpcGenVersion ?? "",
    codeGenName: codeGenName ?? "",
    codeGenVersion: codeGenVersion ?? "",
    schemaName: schemaName ?? "",
    schemaVersion: schemaVersion ?? "",
  };
}

