/* eslint-disable */
// file-upload v1.0.0 63daa500fd686f2d6deddcabe488a6bb99c9664b
// --
// Code generated by Webrpc-gen with typescript generator. DO NOT EDIT.
//
// webrpc-gen -schema=fileupload.ridl -target=typescript -server -out=./interop/server.gen.ts
// Webrpc description and code-gen version
export const WebrpcVersion = "v1"

// Schema version of your RIDL schema
export const WebrpcSchemaVersion = "v1.0.0"

// Schema hash generated from your RIDL schema
export const WebrpcSchemaHash = "63daa500fd686f2d6deddcabe488a6bb99c9664b"


//
// Server interface
//

export interface FileServiceServer<Context = unknown> {
  uploadAvatar(ctx: Context, req: UploadAvatarRequest): Promise<UploadAvatarResponse>
  uploadAttachments(ctx: Context, req: UploadAttachmentsRequest): Promise<UploadAttachmentsResponse>
  downloadAvatar(ctx: Context, req: DownloadAvatarRequest): Promise<Blob | File>
  stampAvatar(ctx: Context, req: StampAvatarRequest): Promise<Blob | File>
  listAvatars(ctx: Context, req: ListAvatarsRequest): Promise<ListAvatarsResponse>
}

//
// Schema types
//

export interface UploadAvatarRequest {
  userId: number
  avatar: Blob | File
}

export interface UploadAvatarResponse {
  size: number
}

export interface UploadAttachmentsRequest {
  userId: number
  attachments: Array<Blob | File>
}

export interface UploadAttachmentsResponse {
  count: number
}

export interface DownloadAvatarRequest {
  userId: number
}

export interface StampAvatarRequest {
  userId: number
  stamp: Blob | File
}

export interface ListAvatarsRequest {
}

export interface ListAvatarsResponse {
  userIds: Array<number>
}




//
// Server handler
//

// serveFileServiceRpc dispatches a web-standard Request to the FileService service
// and returns a web-standard Response, or null when the request path does not
// belong to this service (so the caller can try other routes).
export const serveFileServiceRpc = async <Context>(service: FileServiceServer<Context>, ctx: Context, request: Request): Promise<Response | null> => {
  const pathname = new URL(request.url).pathname
  if (!pathname.startsWith('/rpc/FileService/')) return null
  const method = pathname.slice('/rpc/FileService/'.length)
  if (method === '' || method.includes('/')) return null

  if (request.method !== 'POST') {
    return webrpcErrorResponse(new WebrpcBadMethodError({ cause: `unsupported HTTP method ${request.method} (only POST is allowed)` }), { Allow: 'POST' })
  }

  try {
    return await dispatchFileServiceRequest(service, ctx, method, request)
  } catch (err) {
    return webrpcErrorResponse(err)
  }
}

const dispatchFileServiceRequest = async <Context>(service: FileServiceServer<Context>, ctx: Context, method: string, request: Request): Promise<Response> => {
  switch (method) {
    case 'UploadAvatar': {
      const form = await webrpcUploadFormData(request)
      const payload: any = webrpcParseRequestBody(form.get('json'), 'UploadAvatarRequest')
      webrpcFormFile(form, 'avatar', payload)
      if (!("userId" in payload)) {
        throw new WebrpcBadRequestError({ cause: "missing argument `userId`" })
      }
      if ("userId" in payload && !validateType(payload["userId"], "number")) {
        throw new WebrpcBadRequestError({ cause: "invalid argument: userId" })
      }
      if (!("avatar" in payload)) {
        throw new WebrpcBadRequestError({ cause: "missing argument `avatar`" })
      }
      if ("avatar" in payload && !validateType(payload["avatar"], "file")) {
        throw new WebrpcBadRequestError({ cause: "invalid argument: avatar" })
      }
      const result = await service.uploadAvatar(ctx, payload || {})
      return webrpcJsonResponse(result ?? {})
    }
  
    case 'UploadAttachments': {
      const form = await webrpcUploadFormData(request)
      const payload: any = webrpcParseRequestBody(form.get('json'), 'UploadAttachmentsRequest')
      webrpcFormFiles(form, 'attachments', payload)
      if (!("userId" in payload)) {
        throw new WebrpcBadRequestError({ cause: "missing argument `userId`" })
      }
      if ("userId" in payload && !validateType(payload["userId"], "number")) {
        throw new WebrpcBadRequestError({ cause: "invalid argument: userId" })
      }
      if (!("attachments" in payload)) {
        throw new WebrpcBadRequestError({ cause: "missing argument `attachments`" })
      }
      if ("attachments" in payload && !validateType(payload["attachments"], "file[]")) {
        throw new WebrpcBadRequestError({ cause: "invalid argument: attachments" })
      }
      const result = await service.uploadAttachments(ctx, payload || {})
      return webrpcJsonResponse(result ?? {})
    }
  
    case 'DownloadAvatar': {
      const payload: any = webrpcParseRequestBody(await webrpcRequestBodyText(request), 'DownloadAvatarRequest')
      if (!("userId" in payload)) {
        throw new WebrpcBadRequestError({ cause: "missing argument `userId`" })
      }
      if ("userId" in payload && !validateType(payload["userId"], "number")) {
        throw new WebrpcBadRequestError({ cause: "invalid argument: userId" })
      }
      const result = await service.downloadAvatar(ctx, payload || {})
      return webrpcFileResponse(result)
    }
  
    case 'StampAvatar': {
      const form = await webrpcUploadFormData(request)
      const payload: any = webrpcParseRequestBody(form.get('json'), 'StampAvatarRequest')
      webrpcFormFile(form, 'stamp', payload)
      if (!("userId" in payload)) {
        throw new WebrpcBadRequestError({ cause: "missing argument `userId`" })
      }
      if ("userId" in payload && !validateType(payload["userId"], "number")) {
        throw new WebrpcBadRequestError({ cause: "invalid argument: userId" })
      }
      if (!("stamp" in payload)) {
        throw new WebrpcBadRequestError({ cause: "missing argument `stamp`" })
      }
      if ("stamp" in payload && !validateType(payload["stamp"], "file")) {
        throw new WebrpcBadRequestError({ cause: "invalid argument: stamp" })
      }
      const result = await service.stampAvatar(ctx, payload || {})
      return webrpcFileResponse(result)
    }
  
    case 'ListAvatars': {
      const payload: any = webrpcParseRequestBody(await webrpcRequestBodyText(request), 'ListAvatarsRequest')
      const result = await service.listAvatars(ctx, payload || {})
      return webrpcJsonResponse(result ?? {})
    }
  
    default:
      throw new WebrpcBadRouteError({ cause: 'method not found' })
  }
}


const webrpcContentType = (request: Request): string => {
  return (request.headers.get('Content-Type') || '').split(';')[0]!.trim().toLowerCase()
}

const webrpcRequestBodyText = async (request: Request): Promise<string> => {
  if (webrpcContentType(request) !== 'application/json') {
    throw new WebrpcBadRequestError({ cause: `unsupported Content-Type '${request.headers.get('Content-Type') || ''}' (only application/json is allowed)` })
  }
  return request.text()
}

const webrpcParseRequestBody = (body: unknown, typ: string): any => {
  if (typeof body !== 'string' || body === '') {
    return {}
  }
  let data: any
  try {
    data = JSON.parse(body)
  } catch (err) {
    throw new WebrpcBadRequestError({ cause: `failed to unmarshal request data: ${err instanceof Error ? err.message : String(err)}` })
  }
  try {
    return JsonDecode(data, typ) ?? {}
  } catch (err) {
    throw new WebrpcBadRequestError({ cause: `failed to unmarshal request data: ${err instanceof WebrpcError ? String(err.cause ?? err.message) : err instanceof Error ? err.message : String(err)}` })
  }
}

const webrpcJsonResponse = (data: any): Response => {
  return new Response(JsonEncode(data), {
    status: 200,
    headers: { [WebrpcHeader]: WebrpcHeaderValue, 'Content-Type': 'application/json' },
  })
}

const webrpcErrorResponse = (err: unknown, headers?: { [key: string]: string }): Response => {
  const rpcErr = err instanceof WebrpcError ? err : new WebrpcEndpointError({ cause: err instanceof Error ? err.message : String(err) })
  const body: { [key: string]: any } = { error: rpcErr.name, code: rpcErr.code, msg: rpcErr.message, status: rpcErr.status }
  if (rpcErr.cause !== undefined) {
    body['cause'] = String(rpcErr.cause)
  }
  return new Response(JSON.stringify(body), {
    status: rpcErr.status || 400,
    headers: { ...headers, [WebrpcHeader]: WebrpcHeaderValue, 'Content-Type': 'application/json' },
  })
}


const webrpcUploadFormData = async (request: Request): Promise<FormData> => {
  if (webrpcContentType(request) !== 'multipart/form-data') {
    throw new WebrpcBadRequestError({ cause: `unsupported Content-Type '${request.headers.get('Content-Type') || ''}' (only multipart/form-data is allowed)` })
  }
  try {
    return await request.formData()
  } catch (err) {
    throw new WebrpcBadRequestError({ cause: `failed to parse multipart form: ${err instanceof Error ? err.message : String(err)}` })
  }
}

// webrpcFormFile sets the named file argument from its multipart form part,
// or removes the argument when the part is absent.
const webrpcFormFile = (form: FormData, name: string, args: any) => {
  const file = form.get(name)
  if (file instanceof Blob) {
    args[name] = file
  } else {
    delete args[name]
  }
}

// webrpcFormFiles sets the named repeated file argument from all multipart
// form parts of that name; no parts yield an empty array.
const webrpcFormFiles = (form: FormData, name: string, args: any) => {
  args[name] = form.getAll(name).filter((entry): entry is File => entry instanceof Blob)
}


// webrpcFileResponse streams the file returned by a download method as the
// raw response body, with the file's metadata carried in the headers.
const webrpcFileResponse = (file: Blob | File): Response => {
  if (!(file instanceof Blob)) {
    return webrpcErrorResponse(new WebrpcBadResponseError({ cause: 'download method did not return a file' }))
  }
  const headers = new Headers({
    [WebrpcHeader]: WebrpcHeaderValue,
    'Content-Type': file.type || 'application/octet-stream',
    'Content-Disposition': webrpcContentDisposition(file instanceof File ? file.name : ''),
    'Content-Length': String(file.size),
    'X-Content-Type-Options': 'nosniff',
  })
  return new Response(file, { status: 200, headers })
}

// webrpcContentDisposition formats the attachment Content-Disposition header,
// escaping the filename per RFC 6266 / RFC 5987.
const webrpcContentDisposition = (filename: string): string => {
  if (filename === '') {
    return 'attachment'
  }
  if (/^[\x20-\x21\x23-\x5b\x5d-\x7e]*$/.test(filename)) {
    return `attachment; filename="${filename}"`
  }
  if (/^[\x20-\x7e]*$/.test(filename)) {
    return `attachment; filename="${filename.replace(/([\\"])/g, '\\$1')}"`
  }
  return `attachment; filename*=utf-8''${encodeURIComponent(filename)}`
}



//
// Server type validators
//

const JS_TYPES = [
    "bigint",
    "boolean",
    "function",
    "number",
    "object",
    "string",
    "symbol",
    "undefined"
]

const TYPE_VALIDATORS: { [type: string]: (value: any) => boolean } = {
}

const validateType = (value: any, type: string) => {
  if (type === "file") {
    return value instanceof Blob;
  }
  if (type === "file[]") {
    return Array.isArray(value) && value.every((entry) => entry instanceof Blob);
  }
  if (JS_TYPES.indexOf(type) > -1) {
    return typeof value === type;
  }
  const validator = TYPE_VALIDATORS[type];
  if (!validator) {
    return false;
  }
  return validator(value)
}
//
// File helpers
//


export const JsonEncode = <T = any>(obj: T): string => {
  return JSON.stringify(obj)
}

export const JsonDecode = <T = any>(data: string | any, _typ: string = ''): T => {
  let parsed: any = data
  if (typeof data === 'string') {
    try { parsed = JSON.parse(data) } catch (err) {
      throw WebrpcBadResponseError.new({ cause: `JsonDecode: JSON.parse failed: ${(err as Error).message}` })
    }
  }
  return parsed as T
}


//
// Errors
//

type WebrpcErrorParams = { name?: string, code?: number, message?: string, status?: number, cause?: string }

export class WebrpcError extends Error {
  code: number
  status: number

  constructor(error: WebrpcErrorParams = {}) {
    super(error.message)
    this.name = error.name || 'WebrpcEndpointError'
    this.code = typeof error.code === 'number' ? error.code : 0
    this.message = error.message || `endpoint error`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcError.prototype)
  }

  static new(payload: any): WebrpcError {
    return new this({ message: payload.message, code: payload.code, status: payload.status, cause: payload.cause })
  }
}


export class WebrpcEndpointError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcEndpoint'
    this.code = typeof error.code === 'number' ? error.code : 0
    this.message = error.message || `endpoint error`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcEndpointError.prototype)
  }
}

export class WebrpcRequestFailedError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcRequestFailed'
    this.code = typeof error.code === 'number' ? error.code : -1
    this.message = error.message || `request failed`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcRequestFailedError.prototype)
  }
}

export class WebrpcBadRouteError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcBadRoute'
    this.code = typeof error.code === 'number' ? error.code : -2
    this.message = error.message || `bad route`
    this.status = typeof error.status === 'number' ? error.status : 404
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcBadRouteError.prototype)
  }
}

export class WebrpcBadMethodError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcBadMethod'
    this.code = typeof error.code === 'number' ? error.code : -3
    this.message = error.message || `bad method`
    this.status = typeof error.status === 'number' ? error.status : 405
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcBadMethodError.prototype)
  }
}

export class WebrpcBadRequestError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcBadRequest'
    this.code = typeof error.code === 'number' ? error.code : -4
    this.message = error.message || `bad request`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcBadRequestError.prototype)
  }
}

export class WebrpcBadResponseError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcBadResponse'
    this.code = typeof error.code === 'number' ? error.code : -5
    this.message = error.message || `bad response`
    this.status = typeof error.status === 'number' ? error.status : 500
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcBadResponseError.prototype)
  }
}

export class WebrpcServerPanicError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcServerPanic'
    this.code = typeof error.code === 'number' ? error.code : -6
    this.message = error.message || `server panic`
    this.status = typeof error.status === 'number' ? error.status : 500
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcServerPanicError.prototype)
  }
}

export class WebrpcInternalErrorError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcInternalError'
    this.code = typeof error.code === 'number' ? error.code : -7
    this.message = error.message || `internal error`
    this.status = typeof error.status === 'number' ? error.status : 500
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcInternalErrorError.prototype)
  }
}

export class WebrpcClientAbortedError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcClientAborted'
    this.code = typeof error.code === 'number' ? error.code : -8
    this.message = error.message || `request aborted by client`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcClientAbortedError.prototype)
  }
}

export class WebrpcStreamLostError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcStreamLost'
    this.code = typeof error.code === 'number' ? error.code : -9
    this.message = error.message || `stream lost`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcStreamLostError.prototype)
  }
}

export class WebrpcStreamFinishedError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcStreamFinished'
    this.code = typeof error.code === 'number' ? error.code : -10
    this.message = error.message || `stream finished`
    this.status = typeof error.status === 'number' ? error.status : 200
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcStreamFinishedError.prototype)
  }
}


//
// Schema errors
//

export enum errors {
  WebrpcEndpoint = 'WebrpcEndpoint',
  WebrpcRequestFailed = 'WebrpcRequestFailed',
  WebrpcBadRoute = 'WebrpcBadRoute',
  WebrpcBadMethod = 'WebrpcBadMethod',
  WebrpcBadRequest = 'WebrpcBadRequest',
  WebrpcBadResponse = 'WebrpcBadResponse',
  WebrpcServerPanic = 'WebrpcServerPanic',
  WebrpcInternalError = 'WebrpcInternalError',
  WebrpcClientAborted = 'WebrpcClientAborted',
  WebrpcStreamLost = 'WebrpcStreamLost',
  WebrpcStreamFinished = 'WebrpcStreamFinished',
}

export enum WebrpcErrorCodes {
  WebrpcEndpoint = 0,
  WebrpcRequestFailed = -1,
  WebrpcBadRoute = -2,
  WebrpcBadMethod = -3,
  WebrpcBadRequest = -4,
  WebrpcBadResponse = -5,
  WebrpcServerPanic = -6,
  WebrpcInternalError = -7,
  WebrpcClientAborted = -8,
  WebrpcStreamLost = -9,
  WebrpcStreamFinished = -10,
}

export const webrpcErrorByCode: { [code: number]: any } = {
  [0]: WebrpcEndpointError,
  [-1]: WebrpcRequestFailedError,
  [-2]: WebrpcBadRouteError,
  [-3]: WebrpcBadMethodError,
  [-4]: WebrpcBadRequestError,
  [-5]: WebrpcBadResponseError,
  [-6]: WebrpcServerPanicError,
  [-7]: WebrpcInternalErrorError,
  [-8]: WebrpcClientAbortedError,
  [-9]: WebrpcStreamLostError,
  [-10]: WebrpcStreamFinishedError,
}



//
// Webrpc
//

export const WebrpcHeader = "Webrpc"

export const WebrpcHeaderValue = "webrpc;typescript;file-upload@v1.0.0"

type WebrpcGenVersions = {
  WebrpcGenVersion: string;
  codeGenName: string;
  codeGenVersion: string;
  schemaName: string;
  schemaVersion: string;
};

export function VersionFromHeader(headers: Headers): WebrpcGenVersions {
  const headerValue = headers.get(WebrpcHeader)
  if (!headerValue) {
    return {
      WebrpcGenVersion: "",
      codeGenName: "",
      codeGenVersion: "",
      schemaName: "",
      schemaVersion: "",
    };
  }

  return parseWebrpcGenVersions(headerValue)
}

function parseWebrpcGenVersions(header: string): WebrpcGenVersions {
  const versions = header.split(";")
  if (versions.length < 3) {
    return {
      WebrpcGenVersion: "",
      codeGenName: "",
      codeGenVersion: "",
      schemaName: "",
      schemaVersion: "",
    };
  }

  const [_, WebrpcGenVersion] = versions[0]!.split("@")
  const [codeGenName, codeGenVersion] = versions[1]!.split("@")
  const [schemaName, schemaVersion] = versions[2]!.split("@")

  return {
    WebrpcGenVersion: WebrpcGenVersion ?? "",
    codeGenName: codeGenName ?? "",
    codeGenVersion: codeGenVersion ?? "",
    schemaName: schemaName ?? "",
    schemaVersion: schemaVersion ?? "",
  };
}

