// file-upload v1.0.0 63daa500fd686f2d6deddcabe488a6bb99c9664b
// --
// Code generated by webrpc-gen with golang generator. DO NOT EDIT.
//
// webrpc-gen -schema=fileupload.ridl -target=golang -pkg=main -server -client -out=./fileupload.gen.go
package main

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"maps"
	"mime"
	"mime/multipart"
	"net/http"
	"net/textproto"
	"net/url"
	"slices"
	"strconv"
	"strings"
)

// WebRPC description and code-gen version
func WebRPCVersion() string {
	return "v1"
}

// Schema version of your RIDL schema
func WebRPCSchemaVersion() string {
	return "v1.0.0"
}

// Schema hash generated from your RIDL schema
func WebRPCSchemaHash() string {
	return "63daa500fd686f2d6deddcabe488a6bb99c9664b"
}

//
// Client interface
//

type FileServiceClient interface {
	UploadAvatar(ctx context.Context, userId uint64, avatar *File) (uint64, error)
	UploadAttachments(ctx context.Context, userId uint64, attachments []*File) (uint32, error)
	DownloadAvatar(ctx context.Context, userId uint64) (*File, error)
	// StampAvatar returns the user's stored avatar with the uploaded stamp
	// appended to its content — a combined upload + download method.
	StampAvatar(ctx context.Context, userId uint64, stamp *File) (*File, error)
	// ListAvatars returns the ids of users with a stored avatar — a plain JSON
	// method on a service that also transfers files.
	ListAvatars(ctx context.Context) ([]uint64, error)
}

//
// Server interface
//

type FileServiceServer interface {
	UploadAvatar(ctx context.Context, userId uint64, avatar *File) (uint64, error)
	UploadAttachments(ctx context.Context, userId uint64, attachments []*File) (uint32, error)
	DownloadAvatar(ctx context.Context, userId uint64) (*File, error)
	// StampAvatar returns the user's stored avatar with the uploaded stamp
	// appended to its content — a combined upload + download method.
	StampAvatar(ctx context.Context, userId uint64, stamp *File) (*File, error)
	// ListAvatars returns the ids of users with a stored avatar — a plain JSON
	// method on a service that also transfers files.
	ListAvatars(ctx context.Context) ([]uint64, error)
}

//
// Schema types
//

//
// Client
//

const FileServicePathPrefix = "/rpc/FileService/"

type fileServiceClient struct {
	client HTTPClient
	urls   [5]string
}

func NewFileServiceClient(addr string, client HTTPClient) FileServiceClient {
	prefix := serviceURL(addr, FileServicePathPrefix)
	urls := [5]string{
		prefix + "UploadAvatar",
		prefix + "UploadAttachments",
		prefix + "DownloadAvatar",
		prefix + "StampAvatar",
		prefix + "ListAvatars",
	}
	return &fileServiceClient{
		client: client,
		urls:   urls,
	}
}

func (c *fileServiceClient) UploadAvatar(ctx context.Context, userId uint64, avatar *File) (uint64, error) {
	in := struct {
		Arg0 uint64 `json:"userId"`
		Arg1 *File  `json:"avatar"`
	}{userId, avatar}

	out := struct {
		Ret0 uint64 `json:"size"`
	}{}

	parts := []filePart{}
	parts = append(parts, filePart{name: "avatar", files: []*File{avatar}})
	err := doHTTPUploadRequest(ctx, c.client, c.urls[0], in, parts, &out)

	return out.Ret0, err
}

func (c *fileServiceClient) UploadAttachments(ctx context.Context, userId uint64, attachments []*File) (uint32, error) {
	in := struct {
		Arg0 uint64  `json:"userId"`
		Arg1 []*File `json:"attachments"`
	}{userId, attachments}

	out := struct {
		Ret0 uint32 `json:"count"`
	}{}

	parts := []filePart{}
	parts = append(parts, filePart{name: "attachments", files: attachments})
	err := doHTTPUploadRequest(ctx, c.client, c.urls[1], in, parts, &out)

	return out.Ret0, err
}

func (c *fileServiceClient) DownloadAvatar(ctx context.Context, userId uint64) (*File, error) {
	in := struct {
		Arg0 uint64 `json:"userId"`
	}{userId}

	resp, err := doHTTPRequestRaw(ctx, c.client, c.urls[2], in, nil)
	if err != nil {
		if resp != nil {
			resp.Body.Close()
		}
		return nil, err
	}

	return fileFromResponse(resp), nil
}

func (c *fileServiceClient) StampAvatar(ctx context.Context, userId uint64, stamp *File) (*File, error) {
	in := struct {
		Arg0 uint64 `json:"userId"`
		Arg1 *File  `json:"stamp"`
	}{userId, stamp}

	parts := []filePart{}
	parts = append(parts, filePart{name: "stamp", files: []*File{stamp}})
	resp, err := doHTTPUploadRequestRaw(ctx, c.client, c.urls[3], in, parts, nil)
	if err != nil {
		if resp != nil {
			resp.Body.Close()
		}
		return nil, err
	}

	return fileFromResponse(resp), nil
}

func (c *fileServiceClient) ListAvatars(ctx context.Context) ([]uint64, error) {
	out := struct {
		Ret0 []uint64 `json:"userIds"`
	}{}

	err := doHTTPRequest(ctx, c.client, c.urls[4], nil, &out)

	return out.Ret0, err
}

// Client is a unified client for every service of this API, all sharing the
// same address and HTTP client: c.Users.Get(ctx, …). Skip it when services
// need different transports (e.g. separate admin vs user credentials) — the
// per-service constructors stay.
type Client struct {
	FileService FileServiceClient
}

func NewClient(addr string, client HTTPClient) *Client {
	return &Client{
		FileService: NewFileServiceClient(addr, client),
	}
}

//
// Server
//

type WebRPCServer interface {
	http.Handler
}

type Options struct {
	OnError   func(r *http.Request, rpcErr *WebRPCError)
	OnRequest func(w http.ResponseWriter, r *http.Request) error
	// MaxUploadSize caps multipart/form-data request bodies of file upload
	// methods. Defaults to DefaultMaxUploadSize when zero.
	MaxUploadSize int64
}

type fileServiceService struct {
	FileServiceServer
	OnError       func(r *http.Request, rpcErr *WebRPCError)
	OnRequest     func(w http.ResponseWriter, r *http.Request) error
	MaxUploadSize int64
}

func NewFileServiceServer(svc FileServiceServer, options ...*Options) *fileServiceService {
	server := &fileServiceService{
		FileServiceServer: svc,
	}
	if len(options) > 0 && options[0] != nil {
		server.OnError = options[0].OnError
		server.OnRequest = options[0].OnRequest
		server.MaxUploadSize = options[0].MaxUploadSize
	}
	return server
}

func (s *fileServiceService) Methods() []Method { return methodsFor(ServiceFileService, s) }

func (s *fileServiceService) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	defer func() {
		// In case of a panic, serve a HTTP 500 error and then panic.
		if rr := recover(); rr != nil {
			s.sendErrorJSON(w, r, ErrWebrpcServerPanic.WithCausef("%v", rr))
			panic(rr)
		}
	}()

	w.Header().Set(WebrpcHeader, WebrpcHeaderValue)

	ctx := r.Context()
	ctx = context.WithValue(ctx, HTTPResponseWriterCtxKey, w)
	ctx = context.WithValue(ctx, HTTPRequestCtxKey, r)
	ctx = context.WithValue(ctx, ServiceNameCtxKey, "FileService")

	r = r.WithContext(ctx)

	var handler func(ctx context.Context, w http.ResponseWriter, r *http.Request)
	expectedContentType := "application/json"
	switch r.URL.Path {
	case "/rpc/FileService/UploadAvatar":
		handler = s.serveUploadAvatarMultipart
		expectedContentType = "multipart/form-data"
	case "/rpc/FileService/UploadAttachments":
		handler = s.serveUploadAttachmentsMultipart
		expectedContentType = "multipart/form-data"
	case "/rpc/FileService/DownloadAvatar":
		handler = s.serveDownloadAvatarJSON
	case "/rpc/FileService/StampAvatar":
		handler = s.serveStampAvatarMultipart
		expectedContentType = "multipart/form-data"
	case "/rpc/FileService/ListAvatars":
		handler = s.serveListAvatarsJSON
	default:
		err := ErrWebrpcBadRoute.WithCausef("no webrpc method defined for path %v", r.URL.Path)
		s.sendErrorJSON(w, r, err)
		return
	}

	if r.Method != "POST" {
		w.Header().Add("Allow", "POST") // RFC 9110.
		err := ErrWebrpcBadMethod.WithCausef("unsupported HTTP method %v (only POST is allowed)", r.Method)
		s.sendErrorJSON(w, r, err)
		return
	}

	contentType := r.Header.Get("Content-Type")
	if i := strings.Index(contentType, ";"); i >= 0 {
		contentType = contentType[:i]
	}
	contentType = strings.TrimSpace(strings.ToLower(contentType))

	switch contentType {
	case expectedContentType:
		if s.OnRequest != nil {
			if err := s.OnRequest(w, r); err != nil {
				rpcErr, ok := err.(WebRPCError)
				if !ok {
					rpcErr = ErrWebrpcEndpoint.WithCause(err)
				}
				s.sendErrorJSON(w, r, rpcErr)
				return
			}
		}

		handler(ctx, w, r)
	default:
		err := ErrWebrpcBadRequest.WithCausef("unsupported Content-Type %q (only %s is allowed)", r.Header.Get("Content-Type"), expectedContentType)
		s.sendErrorJSON(w, r, err)
	}
}

func (s *fileServiceService) serveUploadAvatarMultipart(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	ctx = context.WithValue(ctx, MethodNameCtxKey, "UploadAvatar")

	maxUploadSize := s.MaxUploadSize
	if maxUploadSize <= 0 {
		maxUploadSize = DefaultMaxUploadSize
	}
	r.Body = http.MaxBytesReader(w, r.Body, maxUploadSize)

	// Spool the parts (to memory, then to temporary files) so that every file
	// is readable by the time the method implementation is called.
	if err := r.ParseMultipartForm(multipartSpoolMemory); err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to parse multipart form: %w", err))
		return
	}
	defer r.MultipartForm.RemoveAll()

	reqPayload := struct {
		Arg0 uint64 `json:"userId"`
		Arg1 *File  `json:"avatar"`
	}{}

	// The "json" part carries the non-file arguments; it may be absent when
	// the method has none.
	if jsonValue := r.MultipartForm.Value["json"]; len(jsonValue) > 0 {
		if err := json.Unmarshal([]byte(jsonValue[0]), &reqPayload); err != nil {
			s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to unmarshal request data: %w", err))
			return
		}
	}

	var formErr error
	reqPayload.Arg1, formErr = formFile(r.MultipartForm, "avatar")
	if formErr != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCause(formErr))
		return
	}

	// Call service method implementation.
	ret0, err := s.FileServiceServer.UploadAvatar(ctx, reqPayload.Arg0, reqPayload.Arg1)
	if err != nil {
		rpcErr, ok := err.(WebRPCError)
		if !ok {
			rpcErr = ErrWebrpcEndpoint.WithCause(err)
		}
		s.sendErrorJSON(w, r, rpcErr)
		return
	}

	respPayload := struct {
		Ret0 uint64 `json:"size"`
	}{ret0}
	respBody, err := json.Marshal(respPayload)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadResponse.WithCausef("failed to marshal json response: %w", err))
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write(respBody)
}

func (s *fileServiceService) serveUploadAttachmentsMultipart(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	ctx = context.WithValue(ctx, MethodNameCtxKey, "UploadAttachments")

	maxUploadSize := s.MaxUploadSize
	if maxUploadSize <= 0 {
		maxUploadSize = DefaultMaxUploadSize
	}
	r.Body = http.MaxBytesReader(w, r.Body, maxUploadSize)

	// Spool the parts (to memory, then to temporary files) so that every file
	// is readable by the time the method implementation is called.
	if err := r.ParseMultipartForm(multipartSpoolMemory); err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to parse multipart form: %w", err))
		return
	}
	defer r.MultipartForm.RemoveAll()

	reqPayload := struct {
		Arg0 uint64  `json:"userId"`
		Arg1 []*File `json:"attachments"`
	}{}

	// The "json" part carries the non-file arguments; it may be absent when
	// the method has none.
	if jsonValue := r.MultipartForm.Value["json"]; len(jsonValue) > 0 {
		if err := json.Unmarshal([]byte(jsonValue[0]), &reqPayload); err != nil {
			s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to unmarshal request data: %w", err))
			return
		}
	}

	var formErr error
	reqPayload.Arg1, formErr = formFiles(r.MultipartForm, "attachments")
	if formErr != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCause(formErr))
		return
	}

	// Call service method implementation.
	ret0, err := s.FileServiceServer.UploadAttachments(ctx, reqPayload.Arg0, reqPayload.Arg1)
	if err != nil {
		rpcErr, ok := err.(WebRPCError)
		if !ok {
			rpcErr = ErrWebrpcEndpoint.WithCause(err)
		}
		s.sendErrorJSON(w, r, rpcErr)
		return
	}

	respPayload := struct {
		Ret0 uint32 `json:"count"`
	}{ret0}
	respBody, err := json.Marshal(respPayload)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadResponse.WithCausef("failed to marshal json response: %w", err))
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write(respBody)
}

func (s *fileServiceService) serveDownloadAvatarJSON(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	ctx = context.WithValue(ctx, MethodNameCtxKey, "DownloadAvatar")

	reqBody, err := io.ReadAll(r.Body)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to read request data: %w", err))
		return
	}
	defer r.Body.Close()

	reqPayload := struct {
		Arg0 uint64 `json:"userId"`
	}{}
	if err := json.Unmarshal(reqBody, &reqPayload); err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to unmarshal request data: %w", err))
		return
	}

	// Call service method implementation.
	ret0, err := s.FileServiceServer.DownloadAvatar(ctx, reqPayload.Arg0)
	if err != nil {
		rpcErr, ok := err.(WebRPCError)
		if !ok {
			rpcErr = ErrWebrpcEndpoint.WithCause(err)
		}
		s.sendErrorJSON(w, r, rpcErr)
		return
	}

	if ret0 == nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadResponse.WithCausef("method DownloadAvatar returned a nil file"))
		return
	}
	serveFileResponse(w, ret0)
}

func (s *fileServiceService) serveStampAvatarMultipart(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	ctx = context.WithValue(ctx, MethodNameCtxKey, "StampAvatar")

	maxUploadSize := s.MaxUploadSize
	if maxUploadSize <= 0 {
		maxUploadSize = DefaultMaxUploadSize
	}
	r.Body = http.MaxBytesReader(w, r.Body, maxUploadSize)

	// Spool the parts (to memory, then to temporary files) so that every file
	// is readable by the time the method implementation is called.
	if err := r.ParseMultipartForm(multipartSpoolMemory); err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to parse multipart form: %w", err))
		return
	}
	defer r.MultipartForm.RemoveAll()

	reqPayload := struct {
		Arg0 uint64 `json:"userId"`
		Arg1 *File  `json:"stamp"`
	}{}

	// The "json" part carries the non-file arguments; it may be absent when
	// the method has none.
	if jsonValue := r.MultipartForm.Value["json"]; len(jsonValue) > 0 {
		if err := json.Unmarshal([]byte(jsonValue[0]), &reqPayload); err != nil {
			s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to unmarshal request data: %w", err))
			return
		}
	}

	var formErr error
	reqPayload.Arg1, formErr = formFile(r.MultipartForm, "stamp")
	if formErr != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCause(formErr))
		return
	}

	// Call service method implementation.
	ret0, err := s.FileServiceServer.StampAvatar(ctx, reqPayload.Arg0, reqPayload.Arg1)
	if err != nil {
		rpcErr, ok := err.(WebRPCError)
		if !ok {
			rpcErr = ErrWebrpcEndpoint.WithCause(err)
		}
		s.sendErrorJSON(w, r, rpcErr)
		return
	}

	if ret0 == nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadResponse.WithCausef("method StampAvatar returned a nil file"))
		return
	}
	serveFileResponse(w, ret0)
}

func (s *fileServiceService) serveListAvatarsJSON(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	ctx = context.WithValue(ctx, MethodNameCtxKey, "ListAvatars")

	// Call service method implementation.
	ret0, err := s.FileServiceServer.ListAvatars(ctx)
	if err != nil {
		rpcErr, ok := err.(WebRPCError)
		if !ok {
			rpcErr = ErrWebrpcEndpoint.WithCause(err)
		}
		s.sendErrorJSON(w, r, rpcErr)
		return
	}

	respPayload := struct {
		Ret0 []uint64 `json:"userIds"`
	}{ret0}
	respBody, err := json.Marshal(respPayload)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadResponse.WithCausef("failed to marshal json response: %w", err))
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write(respBody)
}

func (s *fileServiceService) sendErrorJSON(w http.ResponseWriter, r *http.Request, rpcErr WebRPCError) {
	if s.OnError != nil {
		s.OnError(r, &rpcErr)
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(rpcErr.HTTPStatus)

	respBody, _ := json.Marshal(rpcErr)
	w.Write(respBody)
}

// Server bundles one handler impl per service; a nil field is not mounted.
type Server struct {
	FileService FileServiceServer
}

// Methods returns the routes of every non-nil service, for explicit per-method mounting.
func (s Server) Methods(opts *Options) []Method {
	var out []Method
	appendIf := func(set bool, srv interface{ Methods() []Method }) {
		if set {
			out = append(out, srv.Methods()...)
		}
	}
	appendIf(s.FileService != nil, NewFileServiceServer(s.FileService, opts))
	return out
}

func RespondWithError(w http.ResponseWriter, err error) {
	rpcErr, ok := err.(WebRPCError)
	if !ok {
		rpcErr = ErrWebrpcEndpoint.WithCause(err)
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(rpcErr.HTTPStatus)

	respBody, _ := json.Marshal(rpcErr)
	w.Write(respBody)
}

type method struct {
	name        string
	service     string
	annotations map[string]string
}

func (m *method) Name() string                   { return m.name }
func (m *method) Service() string                { return m.service }
func (m *method) Annotations() map[string]string { return m.annotations }
func (m *method) Annotation(key string) string   { return m.annotations[key] }
func (m *method) HasAnnotation(key string) bool  { _, ok := m.annotations[key]; return ok }

var methods = map[string]*method{
	"/rpc/FileService/UploadAvatar": {
		name:        "UploadAvatar",
		service:     "FileService",
		annotations: map[string]string{},
	},
	"/rpc/FileService/UploadAttachments": {
		name:        "UploadAttachments",
		service:     "FileService",
		annotations: map[string]string{},
	},
	"/rpc/FileService/DownloadAvatar": {
		name:        "DownloadAvatar",
		service:     "FileService",
		annotations: map[string]string{},
	},
	"/rpc/FileService/StampAvatar": {
		name:        "StampAvatar",
		service:     "FileService",
		annotations: map[string]string{},
	},
	"/rpc/FileService/ListAvatars": {
		name:        "ListAvatars",
		service:     "FileService",
		annotations: map[string]string{},
	},
}

func MethodCtx(ctx context.Context) (*method, bool) {
	req := RequestFromContext(ctx)
	if req == nil {
		return nil, false
	}

	m, ok := methods[req.URL.Path]
	return m, ok
}

type Service string

const (
	ServiceFileService Service = "FileService"
)

// WebrpcMethods returns a copy of all methods, or only those for the given services.
// For further filtering (e.g. by annotation), use maps.DeleteFunc on the result.
func WebrpcMethods(services ...Service) map[string]*method {
	if len(services) == 0 {
		return maps.Clone(methods)
	}
	out := make(map[string]*method)
	for path, m := range methods {
		if slices.Contains(services, Service(m.service)) {
			out[path] = m
		}
	}
	return out
}

var WebRPCServices = map[string][]string{
	"FileService": {
		"UploadAvatar",
		"UploadAttachments",
		"DownloadAvatar",
		"StampAvatar",
		"ListAvatars",
	},
}

// Method pairs an RPC method's metadata with the server that handles it.
// Handler is the server itself, which dispatches by request path.
type Method struct {
	*method
	Path    string
	Handler http.Handler
}

// methodsFor binds every method of service to the handler that serves it.
func methodsFor(service Service, handler http.Handler) []Method {
	var out []Method
	for path, m := range WebrpcMethods(service) {
		out = append(out, Method{method: m, Path: path, Handler: handler})
	}
	return out
}

//
// Client helpers
//

// HTTPClient is the interface used to send HTTP requests. It is fulfilled by *http.Client.
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// serviceURL joins addr (a full URL, e.g. "http://localhost:8080") with the
// service path prefix. Malformed addrs fail on the first request.
func serviceURL(addr, prefix string) string {
	u, err := url.Parse(addr)
	if err != nil || u.Host == "" {
		return addr + prefix
	}
	u.RawQuery, u.Fragment = "", ""
	return u.JoinPath(prefix).String()
}

// newRequest makes an http.Request with common headers.
func newRequest(ctx context.Context, url string, reqBody io.Reader, contentType string) (*http.Request, error) {
	req, err := http.NewRequestWithContext(ctx, "POST", url, reqBody)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Accept", contentType)
	req.Header.Set("Content-Type", contentType)
	req.Header.Set(WebrpcHeader, WebrpcHeaderValue)
	if headers, ok := HTTPRequestHeaders(ctx); ok {
		for k := range headers {
			for _, v := range headers[k] {
				req.Header.Add(k, v)
			}
		}
	}
	return req, nil
}

// doHTTPRequestRaw makes a request and returns the open *http.Response; the caller must close its body.
func doHTTPRequestRaw(ctx context.Context, client HTTPClient, url string, in, out interface{}) (*http.Response, error) {
	reqBody, err := json.Marshal(in)
	if err != nil {
		return nil, ErrWebrpcRequestFailed.WithCausef("failed to marshal JSON body: %w", err)
	}
	if err = ctx.Err(); err != nil {
		return nil, ErrWebrpcRequestFailed.WithCausef("aborted because context was done: %w", err)
	}

	req, err := newRequest(ctx, url, bytes.NewBuffer(reqBody), "application/json")
	if err != nil {
		return nil, ErrWebrpcRequestFailed.WithCausef("could not build request: %w", err)
	}

	resp, err := client.Do(req)
	if err != nil {
		return nil, ErrWebrpcRequestFailed.WithCause(err)
	}

	if resp.StatusCode != 200 {
		respBody, err := io.ReadAll(resp.Body)
		if err != nil {
			return nil, ErrWebrpcBadResponse.WithCausef("failed to read server error response body: %w", err)
		}

		var rpcErr WebRPCError
		if err := json.Unmarshal(respBody, &rpcErr); err != nil {
			return nil, ErrWebrpcBadResponse.WithCausef("failed to unmarshal server error: %w", err)
		}
		if rpcErr.Cause != "" {
			rpcErr.cause = errors.New(rpcErr.Cause)
		}
		return nil, rpcErr
	}

	if out != nil {
		respBody, err := io.ReadAll(resp.Body)
		if err != nil {
			return nil, ErrWebrpcBadResponse.WithCausef("failed to read response body: %w", err)
		}

		err = json.Unmarshal(respBody, &out)
		if err != nil {
			return nil, ErrWebrpcBadResponse.WithCausef("failed to unmarshal JSON response body: %w", err)
		}
	}

	return resp, nil
}

func WithHTTPRequestHeaders(ctx context.Context, h http.Header) (context.Context, error) {
	if _, ok := h["Accept"]; ok {
		return nil, errors.New("provided header cannot set Accept")
	}
	if _, ok := h["Content-Type"]; ok {
		return nil, errors.New("provided header cannot set Content-Type")
	}

	copied := make(http.Header, len(h))
	for k, vv := range h {
		if vv == nil {
			copied[k] = nil
			continue
		}
		copied[k] = make([]string, len(vv))
		copy(copied[k], vv)
	}

	return context.WithValue(ctx, HTTPClientRequestHeadersCtxKey, copied), nil
}

func HTTPRequestHeaders(ctx context.Context) (http.Header, bool) {
	h, ok := ctx.Value(HTTPClientRequestHeadersCtxKey).(http.Header)
	return h, ok
}

// doHTTPRequest makes a request and closes the response body.
func doHTTPRequest(ctx context.Context, client HTTPClient, url string, in, out interface{}) error {
	resp, err := doHTTPRequestRaw(ctx, client, url, in, out)
	if resp != nil {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = ErrWebrpcRequestFailed.WithCausef("failed to close response body: %w", cerr)
		}
	}
	return err
}

//
// Webrpc helpers
//

type contextKey struct {
	name string
}

func (k *contextKey) String() string {
	return "webrpc context value " + k.name
}

var (
	HTTPClientRequestHeadersCtxKey = &contextKey{"HTTPClientRequestHeaders"}
)

var (
	HTTPResponseWriterCtxKey = &contextKey{"HTTPResponseWriter"}
	MethodNameCtxKey         = &contextKey{"MethodName"}
	HTTPRequestCtxKey        = &contextKey{"HTTPRequest"}
	ServiceNameCtxKey        = &contextKey{"ServiceName"}
)

func ServiceNameFromContext(ctx context.Context) string {
	service, _ := ctx.Value(ServiceNameCtxKey).(string)
	return service
}

func MethodNameFromContext(ctx context.Context) string {
	method, _ := ctx.Value(MethodNameCtxKey).(string)
	return method
}

func RequestFromContext(ctx context.Context) *http.Request {
	r, _ := ctx.Value(HTTPRequestCtxKey).(*http.Request)
	return r
}

// Deprecated: Use Go 1.26's new(expr). Migrate automatically with: go fix ./...
func PtrTo[T any](v T) *T { return &v }

func ResponseWriterFromContext(ctx context.Context) http.ResponseWriter {
	w, _ := ctx.Value(HTTPResponseWriterCtxKey).(http.ResponseWriter)
	return w
}

//
// File helpers
//

// File is a file transferred over multipart/form-data (upload methods) or as
// a raw HTTP response body (download methods).
type File struct {
	Name        string // filename, optional
	ContentType string // MIME type as claimed by the sender
	Size        int64  // -1 when unknown
	Body        io.ReadCloser
}

// MarshalJSON implements json.Marshaler. Files are never carried in JSON
// payloads; the field is emitted as null and the file content is transferred
// as a multipart part or as the raw response body instead.
func (f *File) MarshalJSON() ([]byte, error) { return []byte("null"), nil }

// UnmarshalJSON implements json.Unmarshaler as a no-op; files are populated
// from multipart parts, not from JSON payloads.
func (f *File) UnmarshalJSON(b []byte) error { return nil }

// DefaultMaxUploadSize caps multipart/form-data request bodies of file upload
// methods when Options.MaxUploadSize is not set.
const DefaultMaxUploadSize int64 = 32 << 20 // 32 MiB

// multipartSpoolMemory is the memory limit per upload request before parsed
// multipart parts are spooled to temporary files.
const multipartSpoolMemory int64 = 8 << 20 // 8 MiB

// formFile returns the file of the named multipart part, or nil when absent.
func formFile(form *multipart.Form, name string) (*File, error) {
	files, err := formFiles(form, name)
	if err != nil || len(files) == 0 {
		return nil, err
	}
	return files[0], nil
}

// formFiles returns the files of all multipart parts with the given name, or
// nil when absent.
func formFiles(form *multipart.Form, name string) ([]*File, error) {
	headers := form.File[name]
	if len(headers) == 0 {
		return nil, nil
	}
	files := make([]*File, 0, len(headers))
	for _, header := range headers {
		body, err := header.Open()
		if err != nil {
			return nil, fmt.Errorf("failed to open multipart part %q: %w", name, err)
		}
		contentType := header.Header.Get("Content-Type")
		if contentType == "" {
			contentType = "application/octet-stream"
		}
		files = append(files, &File{
			Name:        header.Filename,
			ContentType: contentType,
			Size:        header.Size,
			Body:        body,
		})
	}
	return files, nil
}

// serveFileResponse streams the file as the raw response body and closes it.
func serveFileResponse(w http.ResponseWriter, file *File) {
	defer func() {
		if file.Body != nil {
			file.Body.Close()
		}
	}()

	contentType := file.ContentType
	if contentType == "" {
		contentType = "application/octet-stream"
	}
	w.Header().Set("Content-Type", contentType)
	w.Header().Set("X-Content-Type-Options", "nosniff")
	if file.Name != "" {
		w.Header().Set("Content-Disposition", mime.FormatMediaType("attachment", map[string]string{"filename": file.Name}))
	} else {
		w.Header().Set("Content-Disposition", "attachment")
	}
	if file.Size >= 0 {
		w.Header().Set("Content-Length", strconv.FormatInt(file.Size, 10))
	}
	w.WriteHeader(http.StatusOK)
	if file.Body != nil {
		io.Copy(w, file.Body)
	}
}

// filePart is one file-carrying part of a multipart upload request body.
type filePart struct {
	name  string
	files []*File
}

// doHTTPUploadRequestRaw makes a multipart/form-data request and returns the
// open *http.Response; the caller must close its body. The "json" part with
// the JSON-encoded non-file arguments is sent first, followed by one part per
// file, and the body is streamed (files are not buffered in memory).
func doHTTPUploadRequestRaw(ctx context.Context, client HTTPClient, url string, in interface{}, parts []filePart, out interface{}) (*http.Response, error) {
	jsonBody, err := json.Marshal(in)
	if err != nil {
		return nil, ErrWebrpcRequestFailed.WithCausef("failed to marshal JSON body: %w", err)
	}
	if err = ctx.Err(); err != nil {
		return nil, ErrWebrpcRequestFailed.WithCausef("aborted because context was done: %w", err)
	}

	pr, pw := io.Pipe()
	writer := multipart.NewWriter(pw)
	go func() {
		pw.CloseWithError(func() error {
			jsonPart, err := writer.CreateFormField("json")
			if err != nil {
				return err
			}
			if _, err := jsonPart.Write(jsonBody); err != nil {
				return err
			}
			for _, part := range parts {
				for _, file := range part.files {
					if file == nil {
						continue
					}
					if err := writeFilePart(writer, part.name, file); err != nil {
						return err
					}
				}
			}
			return writer.Close()
		}())
	}()

	req, err := newRequest(ctx, url, pr, writer.FormDataContentType())
	if err != nil {
		return nil, ErrWebrpcRequestFailed.WithCausef("could not build request: %w", err)
	}
	req.Header.Set("Accept", "application/json")

	resp, err := client.Do(req)
	if err != nil {
		return nil, ErrWebrpcRequestFailed.WithCause(err)
	}

	if resp.StatusCode != 200 {
		respBody, err := io.ReadAll(resp.Body)
		if err != nil {
			return nil, ErrWebrpcBadResponse.WithCausef("failed to read server error response body: %w", err)
		}

		var rpcErr WebRPCError
		if err := json.Unmarshal(respBody, &rpcErr); err != nil {
			return nil, ErrWebrpcBadResponse.WithCausef("failed to unmarshal server error: %w", err)
		}
		if rpcErr.Cause != "" {
			rpcErr.cause = errors.New(rpcErr.Cause)
		}
		return nil, rpcErr
	}

	if out != nil {
		respBody, err := io.ReadAll(resp.Body)
		if err != nil {
			return nil, ErrWebrpcBadResponse.WithCausef("failed to read response body: %w", err)
		}

		err = json.Unmarshal(respBody, &out)
		if err != nil {
			return nil, ErrWebrpcBadResponse.WithCausef("failed to unmarshal JSON response body: %w", err)
		}
	}

	return resp, nil
}

// doHTTPUploadRequest makes a multipart/form-data request and closes the
// response body.
func doHTTPUploadRequest(ctx context.Context, client HTTPClient, url string, in interface{}, parts []filePart, out interface{}) error {
	resp, err := doHTTPUploadRequestRaw(ctx, client, url, in, parts, out)
	if resp != nil {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = ErrWebrpcRequestFailed.WithCausef("failed to close response body: %w", cerr)
		}
	}
	return err
}

// multipartQuoteEscaper escapes quotes and backslashes in multipart header
// param values, mirroring mime/multipart.Writer.CreateFormFile.
var multipartQuoteEscaper = strings.NewReplacer("\\", "\\\\", `"`, "\\\"")

// writeFilePart writes one file to the multipart body and closes its Body.
func writeFilePart(writer *multipart.Writer, name string, file *File) error {
	defer func() {
		if file.Body != nil {
			file.Body.Close()
		}
	}()

	fileName := file.Name
	if fileName == "" {
		fileName = name
	}
	contentType := file.ContentType
	if contentType == "" {
		contentType = "application/octet-stream"
	}

	header := make(textproto.MIMEHeader)
	// NOTE: the name and filename params are always quoted, like browsers and
	// mime/multipart.Writer.CreateFormFile do; unquoted params are rejected by
	// strict WHATWG multipart/form-data parsers (e.g. undici's request.formData()).
	header.Set("Content-Disposition", fmt.Sprintf(`form-data; name="%s"; filename="%s"`,
		multipartQuoteEscaper.Replace(name), multipartQuoteEscaper.Replace(fileName)))
	header.Set("Content-Type", contentType)

	part, err := writer.CreatePart(header)
	if err != nil {
		return err
	}
	if file.Body == nil {
		return nil
	}
	_, err = io.Copy(part, file.Body)
	return err
}

// fileFromResponse wraps a raw HTTP response body as a *File. The caller is
// responsible for closing the file's Body.
func fileFromResponse(resp *http.Response) *File {
	file := &File{
		ContentType: resp.Header.Get("Content-Type"),
		Size:        resp.ContentLength,
		Body:        resp.Body,
	}
	if file.ContentType == "" {
		file.ContentType = "application/octet-stream"
	}
	if disposition := resp.Header.Get("Content-Disposition"); disposition != "" {
		if _, params, err := mime.ParseMediaType(disposition); err == nil {
			file.Name = params["filename"]
		}
	}
	return file
}

//
// Errors
//

type WebRPCError struct {
	Name       string `json:"error"`
	Code       int    `json:"code"`
	Message    string `json:"msg"`
	Cause      string `json:"cause,omitempty"`
	HTTPStatus int    `json:"status"`
	cause      error
}

var _ error = WebRPCError{}

func (e WebRPCError) Error() string {
	if e.cause != nil {
		return fmt.Sprintf("%s %d: %s: %v", e.Name, e.Code, e.Message, e.cause)
	}
	return fmt.Sprintf("%s %d: %s", e.Name, e.Code, e.Message)
}

func (e WebRPCError) Is(target error) bool {
	if target == nil {
		return false
	}
	if rpcErr, ok := target.(WebRPCError); ok {
		return rpcErr.Code == e.Code
	}
	return errors.Is(e.cause, target)
}

func (e WebRPCError) Unwrap() error {
	return e.cause
}

func (e WebRPCError) WithCause(cause error) WebRPCError {
	err := e
	err.cause = cause
	err.Cause = cause.Error()
	return err
}

func (e WebRPCError) WithCausef(format string, args ...interface{}) WebRPCError {
	cause := fmt.Errorf(format, args...)
	err := e
	err.cause = cause
	err.Cause = cause.Error()
	return err
}

// Webrpc errors
var (
	ErrWebrpcEndpoint       = WebRPCError{Code: 0, Name: "WebrpcEndpoint", Message: "endpoint error", HTTPStatus: 400}
	ErrWebrpcRequestFailed  = WebRPCError{Code: -1, Name: "WebrpcRequestFailed", Message: "request failed", HTTPStatus: 400}
	ErrWebrpcBadRoute       = WebRPCError{Code: -2, Name: "WebrpcBadRoute", Message: "bad route", HTTPStatus: 404}
	ErrWebrpcBadMethod      = WebRPCError{Code: -3, Name: "WebrpcBadMethod", Message: "bad method", HTTPStatus: 405}
	ErrWebrpcBadRequest     = WebRPCError{Code: -4, Name: "WebrpcBadRequest", Message: "bad request", HTTPStatus: 400}
	ErrWebrpcBadResponse    = WebRPCError{Code: -5, Name: "WebrpcBadResponse", Message: "bad response", HTTPStatus: 500}
	ErrWebrpcServerPanic    = WebRPCError{Code: -6, Name: "WebrpcServerPanic", Message: "server panic", HTTPStatus: 500}
	ErrWebrpcInternalError  = WebRPCError{Code: -7, Name: "WebrpcInternalError", Message: "internal error", HTTPStatus: 500}
	ErrWebrpcClientAborted  = WebRPCError{Code: -8, Name: "WebrpcClientAborted", Message: "request aborted by client", HTTPStatus: 400}
	ErrWebrpcStreamLost     = WebRPCError{Code: -9, Name: "WebrpcStreamLost", Message: "stream lost", HTTPStatus: 400}
	ErrWebrpcStreamFinished = WebRPCError{Code: -10, Name: "WebrpcStreamFinished", Message: "stream finished", HTTPStatus: 200}
)

const WebrpcHeader = "Webrpc"

const WebrpcHeaderValue = "webrpc;golang;file-upload@v1.0.0"

type WebrpcGenVersions struct {
	WebrpcGenVersion string
	CodeGenName      string
	CodeGenVersion   string
	SchemaName       string
	SchemaVersion    string
}

func VersionFromHeader(h http.Header) (*WebrpcGenVersions, error) {
	if h.Get(WebrpcHeader) == "" {
		return nil, fmt.Errorf("header is empty or missing")
	}

	versions, err := parseWebrpcGenVersions(h.Get(WebrpcHeader))
	if err != nil {
		return nil, fmt.Errorf("webrpc header is invalid: %w", err)
	}

	return versions, nil
}

func parseWebrpcGenVersions(header string) (*WebrpcGenVersions, error) {
	versions := strings.Split(header, ";")
	if len(versions) < 3 {
		return nil, fmt.Errorf("expected at least 3 parts while parsing webrpc header: %v", header)
	}

	_, webrpcGenVersion, ok := strings.Cut(versions[0], "@")
	if !ok {
		return nil, fmt.Errorf("webrpc gen version could not be parsed from: %s", versions[0])
	}

	tmplTarget, tmplVersion, ok := strings.Cut(versions[1], "@")
	if !ok {
		return nil, fmt.Errorf("tmplTarget and tmplVersion could not be parsed from: %s", versions[1])
	}

	schemaName, schemaVersion, ok := strings.Cut(versions[2], "@")
	if !ok {
		return nil, fmt.Errorf("schema name and schema version could not be parsed from: %s", versions[2])
	}

	return &WebrpcGenVersions{
		WebrpcGenVersion: webrpcGenVersion,
		CodeGenName:      tmplTarget,
		CodeGenVersion:   tmplVersion,
		SchemaName:       schemaName,
		SchemaVersion:    schemaVersion,
	}, nil
}
