// strictenums v0.0.1 ade5eb2b625a0a9bcb42a96a5586f3f893edaa1a
// --
// Code generated by webrpc-gen@v0.47.0-3-gf3ce9fb with golang generator. DO NOT EDIT.
//
// webrpc-gen -schema=strictenums/strictenums.ridl -target=golang -pkg=strictenums -strictEnums -out=./strictenums/strictenums.gen.go
package strictenums

import (
	"fmt"
)

//
// Schema types
//

type Status uint8

const (
	StatusActive    Status = 0
	StatusArchived  Status = 1
	StatusSuspended Status = 2
)

//go:fix inline
const (
	// Deprecated: Use StatusActive instead.
	Status_active Status = StatusActive
	// Deprecated: Use StatusArchived instead.
	Status_archived Status = StatusArchived
	// Deprecated: Use StatusSuspended instead.
	Status_suspended Status = StatusSuspended
)

var Status_name = map[Status]string{
	StatusActive:    "active",
	StatusArchived:  "archived",
	StatusSuspended: "suspended",
}

var Status_value = map[string]Status{
	"active":    StatusActive,
	"archived":  StatusArchived,
	"suspended": StatusSuspended,
}

func (x Status) String() string {
	return Status_name[x]
}

func (x Status) MarshalText() ([]byte, error) {
	name, ok := Status_name[x]
	if !ok {
		return nil, fmt.Errorf("Status: invalid value %d", x)
	}
	return []byte(name), nil
}

func (x *Status) UnmarshalText(b []byte) error {
	v, ok := Status_value[string(b)]
	if !ok {
		v = Status(^uint8(0))
	}
	*x = v
	return nil
}

// IsValid reports whether x is a declared Status value. An unknown name
// decodes to a reserved invalid value, never to a declared one.
func (x Status) IsValid() bool {
	_, ok := Status_name[x]
	return ok
}

func (x *Status) Is(values ...Status) bool {
	if x == nil {
		return false
	}
	for _, v := range values {
		if *x == v {
			return true
		}
	}
	return false
}

type Level int8

const (
	LevelLow  Level = 0
	LevelHigh Level = 1
)

//go:fix inline
const (
	// Deprecated: Use LevelLow instead.
	Level_low Level = LevelLow
	// Deprecated: Use LevelHigh instead.
	Level_high Level = LevelHigh
)

var Level_name = map[Level]string{
	LevelLow:  "low",
	LevelHigh: "high",
}

var Level_value = map[string]Level{
	"low":  LevelLow,
	"high": LevelHigh,
}

func (x Level) String() string {
	return Level_name[x]
}

func (x Level) MarshalText() ([]byte, error) {
	name, ok := Level_name[x]
	if !ok {
		return nil, fmt.Errorf("Level: invalid value %d", x)
	}
	return []byte(name), nil
}

func (x *Level) UnmarshalText(b []byte) error {
	v, ok := Level_value[string(b)]
	if !ok {
		v = Level(int8(^uint8(0) >> 1))
	}
	*x = v
	return nil
}

// IsValid reports whether x is a declared Level value. An unknown name
// decodes to a reserved invalid value, never to a declared one.
func (x Level) IsValid() bool {
	_, ok := Level_name[x]
	return ok
}

func (x *Level) Is(values ...Level) bool {
	if x == nil {
		return false
	}
	for _, v := range values {
		if *x == v {
			return true
		}
	}
	return false
}

type Project struct {
	Id     uint64 `json:"id"`
	Status Status `json:"status"`
	Level  Level  `json:"level"`
}
