name: server
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  freezed_annotation:
  args: ^1.6.0
  shelf: ^0.7.5
  meta: ^1.1.8

dev_dependencies:
  build_runner:
  freezed:
  extra_pedantic: ^1.2.0
  json_serializable: ^3.3.0
